// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package frontend

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"go.thesmos.sh/eidos/cache"
	"go.thesmos.sh/eidos/core/diag"
	"go.thesmos.sh/eidos/core/directive"
	"go.thesmos.sh/eidos/lang/typescript"
	"go.thesmos.sh/eidos/node"
	"go.thesmos.sh/eidos/plugin"
	"go.thesmos.sh/eidos/store"
)

func TestConvertFileFailures(t *testing.T) {
	t.Parallel()

	t.Run("an unreadable file is reported, not skipped in silence", func(t *testing.T) {
		t.Parallel()
		if os.Geteuid() == 0 {
			t.Skip("running as root: permission bits do not deny a read")
		}
		root := t.TempDir()
		path := filepath.Join(root, "a.ts")
		if err := os.WriteFile(path, []byte("export interface A {}\n"), 0o000); err != nil {
			t.Fatalf("write: %v", err)
		}

		sink := diag.New()
		pkg := &node.Package{Name: "p", Path: root}
		ctx := &plugin.FrontendContext{
			Store: store.New(), Diag: sink,
			Registry: directive.NewRegistry(), Parser: directive.DefaultParser(),
			Cache: cache.NewNone(),
		}
		if convertFile(ctx, pkg, path, defaultOptions()) {
			t.Fatal("an unreadable file reported as converted")
		}
		if len(sink.Diagnostics()) == 0 {
			t.Fatal("an unreadable file produced no diagnostic")
		}
	})

	t.Run("a generated file converts nothing and reports nothing", func(t *testing.T) {
		t.Parallel()
		root := t.TempDir()
		path := filepath.Join(root, "gen.ts")
		body := "// Code generated by eidos. DO NOT EDIT.\n\nexport interface G {}\n"
		if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
			t.Fatalf("write: %v", err)
		}

		sink := diag.New()
		pkg := &node.Package{Name: "p", Path: root}
		ctx := &plugin.FrontendContext{
			Store: store.New(), Diag: sink,
			Registry: directive.NewRegistry(), Parser: directive.DefaultParser(),
			Cache: cache.NewNone(),
		}
		if convertFile(ctx, pkg, path, defaultOptions()) {
			t.Fatal("a generated file reported as converted")
		}
		if len(sink.Diagnostics()) != 0 {
			t.Fatalf("skipping a generated file produced %d diagnostics", len(sink.Diagnostics()))
		}
	})

	t.Run("a directory that yields nothing produces no package", func(t *testing.T) {
		t.Parallel()
		// Every file in it was skipped, so there is no package to add
		// — an empty one would appear in the store as a package that
		// declares nothing.
		root := t.TempDir()
		body := "// Code generated by eidos. DO NOT EDIT.\n"
		if err := os.WriteFile(filepath.Join(root, "g.ts"), []byte(body), 0o600); err != nil {
			t.Fatalf("write: %v", err)
		}

		st := store.New()
		f := New()
		if err := f.Load(&plugin.FrontendContext{
			Store: st, Diag: diag.New(),
			Registry: directive.NewRegistry(), Parser: directive.DefaultParser(),
			Cache: cache.NewNone(), Pattern: root, Fingerprint: "t",
		}); err != nil {
			t.Fatalf("Load: %v", err)
		}

		count := 0
		st.Nodes().Packages().Range(func(*node.Package) bool { count++; return true })
		if count != 0 {
			t.Fatalf("packages = %d, want 0", count)
		}
	})
}

func TestLoadUsesTheProcessDirectory(t *testing.T) {
	t.Parallel()

	t.Run("an unset Dir falls back to the working directory", func(t *testing.T) {
		t.Parallel()
		// Tests run in their package directory, which holds the
		// golden and project fixtures — so resolving relative to the
		// process working directory finds them, and a fallback that
		// failed to resolve would find nothing.
		got, err := expandPattern("./...", Options{})
		if err != nil {
			t.Fatalf("expandPattern with no Dir: %v", err)
		}
		if len(got) == 0 {
			t.Fatal("the working-directory fallback resolved to nothing")
		}
		for _, p := range got {
			if !filepath.IsAbs(p) {
				t.Fatalf("resolved path %q is not absolute", p)
			}
		}
	})

	t.Run("an unresolvable pattern under the fallback still reports no match", func(t *testing.T) {
		t.Parallel()
		_, err := expandPattern("./no-such-dir/...", Options{})
		if !errors.Is(err, ErrNoMatch) {
			t.Fatalf("expandPattern = %v, want ErrNoMatch", err)
		}
	})
}

func TestOverloadEdgeCases(t *testing.T) {
	t.Parallel()

	t.Run("an alternative identical to the declaration is not listed", func(t *testing.T) {
		t.Parallel()
		// The implementation's own spelling is not one of the ways it
		// may be called, so a set whose only alternative repeats it
		// records nothing rather than an empty list.
		decls, _ := convert(t, `
			function f(a: string): void;
			function f(a: string): void {}
		`)
		fn, ok := decls[0].(*node.Function)
		if !ok {
			t.Fatalf("got %T", decls[0])
		}
		if typescript.MetaOverloads.Has(fn.Meta()) {
			got, _ := typescript.MetaOverloads.Get(fn.Meta())
			t.Fatalf("overloads = %+v, want none", got)
		}
	})

	t.Run("a method whose only alternative repeats it records nothing", func(t *testing.T) {
		t.Parallel()
		s := onlyStruct(t, `class C {
			m(a: string): void;
			m(a: string): void {}
		}`)
		if typescript.MetaOverloads.Has(s.Methods[0].Meta()) {
			t.Fatal("a redundant method alternative was recorded")
		}
	})
}
