// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package frontend

import (
	"strings"
	"testing"
)

func TestIsGenerated(t *testing.T) {
	t.Parallel()

	t.Run("recognises the marker in a leading comment block", func(t *testing.T) {
		t.Parallel()
		for _, src := range []string{
			"// Code generated by eidos. DO NOT EDIT.\n\nexport interface A {}\n",
			"// Copyright 2026\n//\n// Code generated by tool. DO NOT EDIT.\n\nexport interface A {}\n",
			"/* a block */\n// Code generated by x. DO NOT EDIT.\n",
		} {
			if !isGenerated([]byte(src)) {
				t.Errorf("marker not recognised in:\n%s", src)
			}
		}
	})

	t.Run("stops at the first line that is not a comment", func(t *testing.T) {
		t.Parallel()
		// The marker means "a tool produced this file". A line
		// matching it below real code is a string or a quoted example,
		// not a header.
		src := "export interface A {}\n// Code generated by eidos. DO NOT EDIT.\n"
		if isGenerated([]byte(src)) {
			t.Fatal("a marker below real code was read as a header")
		}
	})

	t.Run("does not scan an unbounded prologue", func(t *testing.T) {
		t.Parallel()
		// A very long comment banner followed by the marker is past
		// the header window; the bound is what stops a pathological
		// file from being scanned in full.
		src := strings.Repeat("// filler\n", 40) +
			"// Code generated by eidos. DO NOT EDIT.\n"
		if isGenerated([]byte(src)) {
			t.Fatal("the marker was found beyond the header window")
		}
	})

	t.Run("an ordinary file is not generated", func(t *testing.T) {
		t.Parallel()
		for _, src := range []string{
			"",
			"export interface A {}\n",
			"// just a comment\nexport interface A {}\n",
		} {
			if isGenerated([]byte(src)) {
				t.Errorf("ordinary file reported as generated:\n%s", src)
			}
		}
	})
}

func TestFileClassification(t *testing.T) {
	t.Parallel()

	t.Run("recognises every source extension", func(t *testing.T) {
		t.Parallel()
		for _, name := range []string{"a.ts", "a.tsx", "a.mts", "a.cts", "A.TS"} {
			if !hasSourceExtension(name) {
				t.Errorf("%s not recognised as a source file", name)
			}
		}
		for _, name := range []string{"a.js", "a.json", "a", "a.ts.bak"} {
			if hasSourceExtension(name) {
				t.Errorf("%s wrongly recognised as a source file", name)
			}
		}
	})

	t.Run("recognises declaration files across the module variants", func(t *testing.T) {
		t.Parallel()
		for _, name := range []string{"a.d.ts", "a.d.mts", "a.d.cts"} {
			if !isDeclarationFile(name) {
				t.Errorf("%s not recognised as a declaration file", name)
			}
		}
		for _, name := range []string{"a.ts", "declared.ts", "a.dts"} {
			if isDeclarationFile(name) {
				t.Errorf("%s wrongly recognised as a declaration file", name)
			}
		}
	})

	t.Run("recognises both test-file conventions", func(t *testing.T) {
		t.Parallel()
		for _, name := range []string{"a.test.ts", "a.spec.tsx", "deep/b.test.ts"} {
			if !isTestFile(name) {
				t.Errorf("%s not recognised as a test file", name)
			}
		}
		for _, name := range []string{"a.ts", "latest.ts", "respec.ts"} {
			if isTestFile(name) {
				t.Errorf("%s wrongly recognised as a test file", name)
			}
		}
	})

	t.Run("matches a path segment rather than a substring", func(t *testing.T) {
		t.Parallel()
		// A directory named `my_node_modules_helper` contains the
		// substring and is not the thing being excluded.
		if !hasSegment("a/node_modules/pkg/i.ts", "node_modules") {
			t.Error("a real node_modules segment was not matched")
		}
		if hasSegment("a/my_node_modules_helper/i.ts", "node_modules") {
			t.Error("a substring match excluded an unrelated directory")
		}
	})

	t.Run("includeFile honours each option", func(t *testing.T) {
		t.Parallel()
		all := Options{IncludeDeclarations: true, IncludeTests: true, SkipNodeModules: false}
		if !includeFile("a.d.ts", all) || !includeFile("a.test.ts", all) {
			t.Error("permissive options excluded a file")
		}

		strict := Options{SkipNodeModules: true}
		for _, name := range []string{"a.d.ts", "a.test.ts", "x/node_modules/a.ts", "a.js"} {
			if includeFile(name, strict) {
				t.Errorf("strict options admitted %s", name)
			}
		}
	})
}
