// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package typescripttest_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.thesmos.sh/eidos/lang/typescript/typescripttest"
)

func TestAPI(t *testing.T) {
	t.Parallel()

	t.Run("renders the exported surface, sorted", func(t *testing.T) {
		t.Parallel()
		got := parse(t).API()
		for _, want := range []string{
			"import ./models/person",
			"interface User",
			"User extends Base",
			"User.id: ID",
			"User.nick?: string",
			"User.greet(loud: boolean): string",
			"class Repo",
			"Repo implements Store",
			"Repo.find(id: string, ...extra: string[]): User",
			"type ID",
			"enum Role",
			"Role.Admin = 'admin'",
			"function createUser(id: string): User",
			"const MAX: number",
		} {
			if !strings.Contains(got, want+"\n") {
				t.Errorf("the surface does not carry %q:\n%s", want, got)
			}
		}
	})

	t.Run("what a consumer cannot see is left out", func(t *testing.T) {
		t.Parallel()
		// Doc comments, bodies and member order are none of a
		// consumer's business, and including them would make the golden
		// churn on changes their code never sees.
		src := `// Code generated by eidos. DO NOT EDIT.

/**
 * A user of the system.
 */
export interface User {
  id: string;
}

interface Hidden {
  x: string;
}
`
		got := typescripttest.Parse(t, typescripttest.TSFile("u.ts", src)).API()
		if strings.Contains(got, "Hidden") {
			t.Errorf("an unexported declaration reached the surface:\n%s", got)
		}
		if strings.Contains(got, "A user of the system") {
			t.Errorf("a doc comment reached the surface:\n%s", got)
		}
	})

	t.Run("reordering members produces no diff", func(t *testing.T) {
		t.Parallel()
		// Which is the whole point: a generator that reorders without
		// changing what it offers should not make a reviewer read two
		// hundred lines.
		first := "export interface U {\n  a: string;\n  b: number;\n}\n"
		second := "export interface U {\n  b: number;\n  a: string;\n}\n"
		if a, b := api(t, first), api(t, second); a != b {
			t.Fatalf("reordering changed the surface:\n--- a ---\n%s--- b ---\n%s", a, b)
		}
	})

	t.Run("imports are part of the surface", func(t *testing.T) {
		t.Parallel()
		// Unlike Go's rendering of the same idea: an added specifier is
		// a package the consumer's project must resolve.
		got := api(t, "import type { A } from './a';\nexport type B = A;\n")
		if !strings.Contains(got, "import ./a") {
			t.Fatal("an import did not reach the surface")
		}
	})

	t.Run("a changed signature is one line replaced", func(t *testing.T) {
		t.Parallel()
		before := api(t, "export function f(a: string): void {}\n")
		after := api(t, "export function f(a: number): void {}\n")
		if before == after {
			t.Fatal("a changed signature produced no diff")
		}
	})
}

func TestAssertAPIGolden(t *testing.T) {
	t.Parallel()

	t.Run("a matching surface passes", func(t *testing.T) {
		t.Parallel()
		s := parse(t)
		path := filepath.Join(t.TempDir(), "user.api")
		if err := os.WriteFile(path, []byte(s.API()), 0o600); err != nil {
			t.Fatalf("seed golden: %v", err)
		}
		typescripttest.AssertAPIGolden(t, s, path)
	})

	t.Run("a changed surface is reported", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "user.api")
		if err := os.WriteFile(path, []byte("type Something\n"), 0o600); err != nil {
			t.Fatalf("seed golden: %v", err)
		}
		s := probe(t)
		typescripttest.AssertAPIGolden(s, parse(t), path)
		if !s.failed {
			t.Fatal("a changed surface passed")
		}
	})
}

// api renders one source's exported surface.
func api(t *testing.T, src string) string {
	t.Helper()
	return typescripttest.Parse(t, typescripttest.TSFile("x.ts", src)).API()
}
