// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package typescripttest_test

import (
	"fmt"
	"strings"
	"testing"

	"go.thesmos.sh/eidos/lang/typescript/typescripttest"
)

// primary is a generated file shaped like the ones the corpus
// produces: a generated header, an import, an alias, an enum, an
// interface with a heritage clause and a class.
const primary = `// Code generated by eidos. DO NOT EDIT.

import type { Person } from './models/person';

export type ID = string;

export enum Role {
  Admin = 'admin',
  Guest = 'guest',
}

export interface User extends Base {
  id: ID;
  nick?: string;
  tags: string[];
  owner: Person | null;
  greet(loud: boolean): string;
}

export declare class Repo implements Store {
  private readonly cache: Record<string, User>;
  find(id: string, ...extra: string[]): User;
}

export declare const MAX: number;

export declare function createUser(id: string): User;
`

// broken is what a template with an unclosed brace emits: output that
// every substring check passes against and no parser accepts.
const broken = `// Code generated by eidos. DO NOT EDIT.

export interface User {
  id: string;
`

// mistyped parses cleanly and is wrong — the property is declared
// `number` where the module it imports from says `string`. Nothing
// but a type check finds it.
const mistyped = `// Code generated by eidos. DO NOT EDIT.

import type { User } from './user';

export interface Echo {
  id: number;
}

export declare function take(u: User): Echo;
`

// supportModule is the hand-written module the generated output
// imports from — the file a consumer wrote, without which none of the
// output type-checks.
const supportModule = `export interface User {
  id: string;
}
`

// parse returns the corpus file, parsed.
func parse(t *testing.T) *typescripttest.Source {
	t.Helper()
	return typescripttest.Parse(t, typescripttest.TSFile("user.gen.ts", primary))
}

// spy captures what an assertion reported instead of failing the
// test, so a test can assert that a failing assertion fails — and
// that its message diagnoses rather than merely denies, which is most
// of what these assertions are for.
//
// The embedded TB delegates everything else, so a spy is a drop-in
// for the real one at every call site.
type spy struct {
	testing.TB

	failed  bool
	skipped bool
	msg     string
}

func (s *spy) Errorf(format string, args ...any) {
	s.record(fmt.Sprintf(format, args...))
}

// Fatalf records and returns.
//
// The real one stops the goroutine, which would make every
// stop-the-test branch untestable. Returning is safe only because the
// assertions that use Fatalf return a nil or zero value immediately
// after, and the tests below check that rather than dereferencing it.
func (s *spy) Fatalf(format string, args ...any) {
	s.record(fmt.Sprintf(format, args...))
}

// Error records the message a bare Error reported.
func (s *spy) Error(args ...any) {
	s.record(fmt.Sprint(args...))
}

// record appends one report.
//
// Accumulated rather than replaced, because a real TB does: an
// assertion whose guard reports and then — with a spy, which cannot
// stop the goroutine — carries on to report something else would
// otherwise have the first message overwritten, and the test would be
// asserting on whichever came last.
func (s *spy) record(msg string) {
	s.failed = true
	if s.msg != "" {
		s.msg += "\n"
	}
	s.msg += msg
}

// Skip records rather than stopping, for the same reason Fatalf does.
//
// Appended rather than replacing, so a guard that reported before the
// toolchain was probed for is still readable — a real TB would have
// stopped at the guard and never reached the skip.
func (s *spy) Skip(args ...any) {
	s.skipped = true
	if s.msg != "" {
		s.msg += "\n"
	}
	s.msg += fmt.Sprint(args...)
}

// probe returns a spy over t.
func probe(t *testing.T) *spy {
	t.Helper()
	return &spy{TB: t}
}

// assertReports requires that the assertion failed and that its
// message names each of the given fragments.
//
// The fragments are the point: an assertion that merely says "not
// found" sends the reader back to the generated file to work out
// what *is* there, which is the whole cost these assertions exist to
// remove.
func assertReports(t *testing.T, s *spy, fragments ...string) {
	t.Helper()
	if !s.failed {
		t.Fatalf("the assertion passed; it should have reported %v", fragments)
	}
	for _, want := range fragments {
		if !strings.Contains(s.msg, want) {
			t.Errorf("the message does not mention %q: %s", want, s.msg)
		}
	}
}
