// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package typescripttest_test

import (
	"os"
	"path/filepath"
	"testing"

	"go.thesmos.sh/eidos/lang/typescript/typescripttest"
)

func TestProjectOptions(t *testing.T) {
	t.Parallel()

	t.Run("a local package is importable by name", func(t *testing.T) {
		t.Parallel()
		// The common case neither WithSource nor InProject serves:
		// output importing the generator's own runtime library, one
		// package, sitting in the same repository.
		lib := t.TempDir()
		write(t, lib, "package.json", `{"name":"@acme/runtime","type":"module","types":"index.ts"}`)
		write(t, lib, "index.ts", "export interface Tagged {\n  tag: string;\n}\n")

		typescripttest.
			Of(typescripttest.TSFile("user.gen.ts", `// Code generated by eidos. DO NOT EDIT.

import type { Tagged } from '@acme/runtime';

export interface User extends Tagged {
  id: string;
}
`)).
			WithDependency("@acme/runtime", lib).
			AssertTypeChecks(t)
	})

	t.Run("a base project brings its own configuration", func(t *testing.T) {
		t.Parallel()
		// The escape hatch for output checked against what the consumer
		// actually has, rather than against a synthetic tsconfig.
		base := t.TempDir()
		write(t, base, "package.json", `{"name":"consumer","type":"module"}`)
		write(t, base, "tsconfig.json",
			`{"compilerOptions":{"strict":false,"noEmit":true},"include":["**/*.ts"]}`)
		write(t, base, "user.ts", "export interface User {\n  id: string;\n}\n")

		// Loose enough that the base project's own settings are what
		// decide the answer: this fails under the strict defaults.
		typescripttest.
			Of(typescripttest.TSFile("loose.gen.ts", looselyTyped)).
			InProject(base).
			AssertTypeChecks(t)
	})

	t.Run("the two cannot be combined", func(t *testing.T) {
		t.Parallel()
		// Composing them would mean merging into a node_modules this
		// package did not assemble, and either outcome runs while only
		// one is what the caller asked for.
		s := probe(t)
		typescripttest.
			Of(typescripttest.TSFile("a.gen.ts", primary)).
			InProject(t.TempDir()).
			WithDependency("x", t.TempDir()).
			AssertTypeChecks(s)
		assertReports(t, s, "InProject and WithDependency cannot both be set")
	})

	t.Run("a target below what the output needs is reported", func(t *testing.T) {
		t.Parallel()
		// A template that starts emitting a construct from a later
		// edition raises the floor of every project that runs the
		// generator, and nothing else notices.
		s := probe(t)
		typescripttest.
			Of(typescripttest.TSFile("modern.gen.ts", `// Code generated by eidos. DO NOT EDIT.

export declare class Holder {
  #secret: string;
}
`)).
			WithTarget("ES5").
			AssertTypeChecks(s)
		if s.skipped {
			t.Skip("no TypeScript compiler; the assertion itself was not exercised")
		}
		assertReports(t, s, "modern.gen.ts")
	})

	t.Run("a self-reference resolves against the project's name", func(t *testing.T) {
		t.Parallel()
		// Output that imports its own package by name rather than by
		// relative path is resolved through the package's own name, so
		// a project named anything else reports it unresolved.
		s := probe(t)
		typescripttest.
			Of(typescripttest.TSFile("user.gen.ts",
				"import type { X } from '@acme/models';\nexport type Y = X;\n")).
			AssertTypeChecks(s)
		if s.skipped {
			t.Skip("no TypeScript compiler; the assertion itself was not exercised")
		}
		assertReports(t, s, "@acme/models")
	})

	t.Run("compiler options reach the check", func(t *testing.T) {
		t.Parallel()
		typescripttest.
			Of(typescripttest.TSFile("loose.ts", looselyTyped)).
			WithCompilerOptions(map[string]any{"strict": false}).
			AssertTypeChecks(t)
	})
}

// write puts one file into a directory a fixture is assembling.
func write(t *testing.T, dir, name, body string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(body+"\n"), 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}
