// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package typescripttest_test

import (
	"testing"

	"go.thesmos.sh/eidos/lang/typescript/typescripttest"
)

// The contract module a generated double stands in for, and the
// doubles themselves — one that satisfies it and three near misses
// that parse cleanly, type-check in isolation, and satisfy nothing.
const (
	contractModule = `export interface Printer {
  print(...args: string[]): void;
  name?: string;
}
`

	// good declares the contract's shape exactly.
	good = `// Code generated by eidos. DO NOT EDIT.

export interface PrinterStub {
  print(...args: string[]): void;
  name?: string;
}
`

	// flattenedRest takes one array where the contract takes many
	// arguments. A frontend records a rest parameter by its element
	// type, so this is the shape a projection that dropped the marker
	// produces.
	flattenedRest = `// Code generated by eidos. DO NOT EDIT.

export interface PrinterStub {
  print(args: string[]): void;
  name?: string;
}
`

	// missingMethod drops the contract's only required member, which
	// is what a projection that lost a method through an embed
	// produces.
	missingMethod = `// Code generated by eidos. DO NOT EDIT.

export interface PrinterStub {
  name?: string;
}
`
)

func TestAssertSatisfies(t *testing.T) {
	t.Parallel()

	t.Run("a double matching the contract passes", func(t *testing.T) {
		t.Parallel()
		doubling(good).AssertSatisfies(t, "PrinterStub", "Printer")
	})

	t.Run("a dropped rest marker is caught", func(t *testing.T) {
		t.Parallel()
		// Nothing structural sees it: the method is there, the name is
		// right, and only the checker knows a caller passing two
		// arguments is rejected.
		s := probe(t)
		doubling(flattenedRest).AssertSatisfies(s, "PrinterStub", "Printer")
		if s.skipped {
			t.Skip("no TypeScript compiler; the assertion itself was not exercised")
		}
		assertReports(t, s, "PrinterStub", "satisfy")
	})

	t.Run("several claims are proved in one check", func(t *testing.T) {
		t.Parallel()
		// N claims would otherwise cost N compiler runs for what is one
		// file of N lines.
		doubling(good).AssertSatisfiesAll(t,
			typescripttest.Satisfaction{Type: "PrinterStub", Interface: "Printer"},
			typescripttest.Satisfaction{Type: "PrinterStub", Interface: "Printer"},
		)
	})

	t.Run("no claims proves nothing and says so", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		doubling(good).AssertSatisfiesAll(s)
		assertReports(t, s, "proves nothing")
	})

	t.Run("an interface covering a contract is stated directly", func(t *testing.T) {
		t.Parallel()
		// The relation a generator emitting an interface promises, and
		// the one every plugin in this position hand-wrote into a
		// support file.
		doubling(good).AssertInterfaceSatisfies(t, "PrinterStub", "Printer")
	})

	t.Run("a contract from the primary module needs no From", func(t *testing.T) {
		t.Parallel()
		// Which is where a generator emitting both puts them.
		typescripttest.
			Of(typescripttest.TSFile("both.gen.ts", `// Code generated by eidos. DO NOT EDIT.

export interface Port {
  get(): string;
}

export interface PortStub {
  get(): string;
}
`)).
			AssertSatisfies(t, "PortStub", "Port")
	})
}

func TestAssertDoesNotSatisfy(t *testing.T) {
	t.Parallel()

	t.Run("a near miss is proved to be one", func(t *testing.T) {
		t.Parallel()
		// What a shape detector actually claims: not that the canonical
		// shape passes but that every near miss fails.
		doubling(flattenedRest).AssertDoesNotSatisfy(t, "PrinterStub", "Printer")
		doubling(missingMethod).AssertDoesNotSatisfy(t, "PrinterStub", "Printer")
	})

	t.Run("a real match is reported", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		doubling(good).AssertDoesNotSatisfy(s, "PrinterStub", "Printer")
		if s.skipped {
			t.Skip("no TypeScript compiler; the assertion itself was not exercised")
		}
		assertReports(t, s, "which it must not", "near miss")
	})

	t.Run("output that does not type-check proves nothing either way", func(t *testing.T) {
		t.Parallel()
		// A misspelled contract, a support module that stopped
		// compiling, or an import the fixture forgot all fail the
		// assertion file just as well, and each makes the negative pass
		// for the wrong reason.
		s := probe(t)
		typescripttest.
			Of(typescripttest.TSFile("broken.gen.ts", `// Code generated by eidos. DO NOT EDIT.

import type { Missing } from './absent';

export interface Echo {
  x: Missing;
}

export interface Printer {
  x: string;
}
`)).
			AssertDoesNotSatisfy(s, "Echo", "Printer")
		if s.skipped {
			t.Skip("no TypeScript compiler; the assertion itself was not exercised")
		}
		assertReports(t, s, "does not type-check on its own", "would prove nothing")
	})
}

func TestSatisfactionArguments(t *testing.T) {
	t.Parallel()

	t.Run("a type expression is refused with the reason", func(t *testing.T) {
		t.Parallel()
		// The assertion imports the name, and an import binds one
		// identifier — so this is the caller's error rather than the
		// generator's, and reaching tsc would report it against a line
		// they cannot see.
		for _, bad := range []string{"Box<string>", "./user.User", "A | B", ""} {
			s := probe(t)
			doubling(good).AssertSatisfies(s, bad, "Printer")
			assertReports(t, s, "Type")
		}
	})
}

// doubling returns a fixture whose output is src and whose support
// module declares the contract.
func doubling(src string) *typescripttest.Generated {
	return typescripttest.
		Of(typescripttest.TSFile("printer_stub.gen.ts", src)).
		WithSource(typescripttest.TSFile("printer.ts", contractModule))
}
