// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package typescripttest_test

import (
	"strings"
	"testing"

	"go.thesmos.sh/eidos/lang/typescript/typescripttest"
)

// A generated module with bodies, which the corpus in helpers_test.go
// deliberately has none of: a scope assertion is about what is inside
// one declaration, so the fixture needs several that differ.
const bodied = `// Code generated by eidos. DO NOT EDIT.

export const chain = [
  withLogging,
  withRetry,
  withTracing,
];

export function build(): string {
  const first = prepare();
  const second = finish();
  return first + second;
}

export class Repo {
  find(id: string): string {
    validate(id);
    return lookup(id);
  }

  reset(): void {
  }
}

export interface Port {
  find(id: string): string;
}

export const bare: string = 'x';
`

func TestScopes(t *testing.T) {
	t.Parallel()

	t.Run("a function's body is reachable on its own", func(t *testing.T) {
		t.Parallel()
		// A substring matched against the whole file cannot say which
		// declaration carries it, so a check meaning "this one calls
		// prepare" ends up counting occurrences and inferring.
		body := bodies(t).InFunction(t, "build").Body()
		if !strings.Contains(body, "prepare()") {
			t.Fatalf("body = %q", body)
		}
	})

	t.Run("a method's body is scoped to its declaration", func(t *testing.T) {
		t.Parallel()
		// Two classes declaring `find` are ordinary, and a file-wide
		// check cannot tell one from the other.
		bodies(t).InMethod(t, "Repo", "find").
			AssertContains(t, "validate(id)").
			AssertNotContains(t, "prepare()")
	})

	t.Run("a binding's initialiser is the scope", func(t *testing.T) {
		t.Parallel()
		// The scope a slot host most often renders into: contributions
		// land inside an array as readily as inside a function.
		bodies(t).InBinding(t, "chain").
			AssertContains(t, "withRetry").
			AssertOrderAll(t, "withLogging", "withRetry", "withTracing")
	})

	t.Run("a repeated contribution is counted", func(t *testing.T) {
		t.Parallel()
		// A slot appended to twice renders the same line twice, which
		// every "contains" check passes.
		bodies(t).InBinding(t, "chain").
			AssertCount(t, "withRetry", 1).
			AssertCount(t, "withMissing", 0)

		s := probe(t)
		bodies(t).InBinding(s, "chain").AssertCount(s, "withRetry", 2)
		assertReports(t, s, "1 times, want 2")
	})

	t.Run("order within a scope is asserted", func(t *testing.T) {
		t.Parallel()
		bodies(t).InFunction(t, "build").AssertOrder(t, "first", "second")

		s := probe(t)
		bodies(t).InFunction(s, "build").AssertOrder(s, "second", "first")
		assertReports(t, s, "after")
	})

	t.Run("a missing part is reported by name", func(t *testing.T) {
		t.Parallel()
		first := probe(t)
		bodies(t).InFunction(first, "build").AssertOrder(first, "absent", "first")
		assertReports(t, first, "absent")

		second := probe(t)
		bodies(t).InFunction(second, "build").AssertOrder(second, "first", "absent")
		assertReports(t, second, "absent")
	})

	t.Run("spacing is not part of the assertion", func(t *testing.T) {
		t.Parallel()
		bodies(t).InFunction(t, "build").AssertContains(t, "const  first  =  prepare()")
	})

	t.Run("a forbidden substring is reported", func(t *testing.T) {
		t.Parallel()
		bodies(t).InMethod(t, "Repo", "reset").AssertNotContains(t, "lookup")

		s := probe(t)
		bodies(t).InMethod(s, "Repo", "find").AssertNotContains(s, "lookup")
		assertReports(t, s, "must not")
	})
}

func TestScopeFailures(t *testing.T) {
	t.Parallel()

	t.Run("an absent declaration reports and asserts nothing further", func(t *testing.T) {
		t.Parallel()
		// The assertions on a scope that was not found stay quiet, so
		// one missing declaration produces one failure rather than one
		// per assertion chained after it.
		s := probe(t)
		sc := bodies(t).InFunction(s, "absent")
		assertReports(t, s, "absent")

		quiet := probe(t)
		sc.AssertContains(quiet, "anything").
			AssertNotContains(quiet, "anything").
			AssertCount(quiet, "anything", 3).
			AssertOrder(quiet, "a", "b")
		if quiet.failed {
			t.Errorf("a not-found scope kept asserting: %s", quiet.msg)
		}
		if sc.Body() != "" {
			t.Errorf("a not-found scope has a body: %q", sc.Body())
		}
	})

	t.Run("a signature has no body to scope to", func(t *testing.T) {
		t.Parallel()
		// An interface method is a signature, and an empty scope every
		// assertion then passes against would be worse than a report.
		s := probe(t)
		bodies(t).InMethod(s, "Port", "find")
		assertReports(t, s, "signature with no body")
	})

	t.Run("an absent method is reported by name", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		bodies(t).InMethod(s, "Repo", "absent")
		assertReports(t, s, "Repo.absent")
	})

	t.Run("a binding with no initialiser is reported", func(t *testing.T) {
		t.Parallel()
		src := "export declare const declared: string;\n"
		s := probe(t)
		typescripttest.
			Parse(t, typescripttest.TSFile("d.ts", src)).
			InBinding(s, "declared")
		assertReports(t, s, "no initialiser")
	})

	t.Run("an absent binding is reported with what is there", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		bodies(t).InBinding(s, "absent")
		assertReports(t, s, "absent", "chain")
	})
}

// bodies parses the corpus with declaration bodies in it.
func bodies(t *testing.T) *typescripttest.Source {
	t.Helper()
	return typescripttest.Parse(t, typescripttest.TSFile("chain.gen.ts", bodied))
}
