// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package typescripttest_test

import (
	"strings"
	"testing"

	"go.thesmos.sh/eidos/lang/typescript/typescripttest"
)

// A generated test suite, in the shape a generator emitting one per
// contract produces: an outer describe per subject, cases inside it,
// and a second suite so a file-wide list can go wrong.
const generatedSuite = `// Code generated by eidos. DO NOT EDIT.

import { describe, it } from 'node:test';
import assert from 'node:assert';

describe.concurrent('PrinterStub', () => {
  it('records what it was called with', () => {
    assert.ok(true);
  });
  it('answers with the value pinned by returns', () => {
    assert.ok(true);
  });
});

describe('CloserStub', () => {
  it('records what it was called with', () => {
    assert.ok(true);
  });
});
`

// nodeSuite is what a generator targeting Node's own runner emits:
// `suite` and `test` rather than `describe` and `it`, and a passing
// assertion so the runner has something to report.
const nodeSuite = `// Code generated by eidos. DO NOT EDIT.

import { suite, test } from 'node:test';
import assert from 'node:assert';
import { greet } from './greeter.ts';

suite('greeter', () => {
  test('greets by name', () => {
    assert.equal(greet('Roy'), 'hello Roy');
  });
});
`

// greeter is the module nodeSuite exercises.
const greeter = `export function greet(name: string): string {
  return 'hello ' + name;
}
`

func TestSuites(t *testing.T) {
	t.Parallel()

	t.Run("every top-level suite is named in order", func(t *testing.T) {
		t.Parallel()
		got := suite(t).Suites()
		if strings.Join(got, ",") != "PrinterStub,CloserStub" {
			t.Fatalf("Suites = %v", got)
		}
	})

	t.Run("both vocabularies are recognised", func(t *testing.T) {
		t.Parallel()
		// `describe`/`it` are Jasmine's, inherited by Jest, Mocha and
		// Vitest; `suite`/`test` are Node's. A harness recognising one
		// would report every suite the other emits as absent.
		got := typescripttest.
			Parse(t, typescripttest.TSFile("node.test.ts", nodeSuite)).
			Suites()
		if strings.Join(got, ",") != "greeter" {
			t.Fatalf("Suites = %v", got)
		}
	})

	t.Run("the whole suite list is pinned", func(t *testing.T) {
		t.Parallel()
		suite(t).AssertSuites(t, "PrinterStub", "CloserStub")

		s := probe(t)
		suite(t).AssertSuites(s, "PrinterStub")
		assertReports(t, s, "PrinterStub CloserStub")
	})

	t.Run("a modifier does not hide a suite", func(t *testing.T) {
		t.Parallel()
		// `describe.concurrent` and `describe.skip` are the same
		// declaration with a different runner instruction.
		if got := suite(t).Suites()[0]; got != "PrinterStub" {
			t.Fatalf("the modified suite was named %q", got)
		}
	})
}

func TestCases(t *testing.T) {
	t.Parallel()

	t.Run("cases are scoped to their suite", func(t *testing.T) {
		t.Parallel()
		// A generator emitting the same case name under two contracts
		// is emitting what a consumer expects, and a file-wide list
		// would report it as a duplicate.
		got := suite(t).Cases(t, "CloserStub")
		if strings.Join(got, ",") != "records what it was called with" {
			t.Fatalf("Cases = %v", got)
		}
		if n := len(suite(t).Cases(t, "PrinterStub")); n != 2 {
			t.Fatalf("PrinterStub has %d cases, want 2", n)
		}
	})

	t.Run("a case is asserted by name", func(t *testing.T) {
		t.Parallel()
		suite(t).
			AssertCase(t, "PrinterStub", "records what it was called with").
			AssertNoCase(t, "PrinterStub", "does something else")
	})

	t.Run("a renamed case is reported with the ones that exist", func(t *testing.T) {
		t.Parallel()
		// The failure is nearly always a renamed case rather than a
		// missing one, and a bare "not found" sends the reader to the
		// generator that emitted it.
		s := probe(t)
		suite(t).AssertCase(s, "PrinterStub", "records the call")
		assertReports(t, s, "records the call", "records what it was called with")
	})

	t.Run("a case that must not be there is reported", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		suite(t).AssertNoCase(s, "PrinterStub", "records what it was called with")
		assertReports(t, s, "must not")
	})

	t.Run("an absent suite is reported by name", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		suite(t).Cases(s, "Absent")
		assertReports(t, s, "Absent", "PrinterStub")
	})
}

func TestAssertConcurrent(t *testing.T) {
	t.Parallel()

	t.Run("a concurrent suite passes", func(t *testing.T) {
		t.Parallel()
		suite(t).AssertConcurrent(t, "PrinterStub")
	})

	t.Run("a serial suite is reported", func(t *testing.T) {
		t.Parallel()
		// A generated suite that dropped it slows every consumer's
		// build without failing anything.
		s := probe(t)
		suite(t).AssertConcurrent(s, "CloserStub")
		assertReports(t, s, "CloserStub", "without concurrency")
	})

	t.Run("Node's spelling counts too", func(t *testing.T) {
		t.Parallel()
		src := "import { suite } from 'node:test';\n" +
			"suite('s', { concurrency: true }, () => {});\n"
		typescripttest.
			Parse(t, typescripttest.TSFile("n.test.ts", src)).
			AssertConcurrent(t, "s")
	})

	t.Run("an absent suite is reported", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		suite(t).AssertConcurrent(s, "Absent")
		assertReports(t, s, "Absent")
	})
}

func TestAssertTestsPass(t *testing.T) {
	t.Parallel()

	t.Run("a passing generated suite passes", func(t *testing.T) {
		t.Parallel()
		// The loop nothing else closes: asserting that a case of some
		// name exists passes just as well when the case is empty.
		typescripttest.
			Of(typescripttest.TSFile("greeter.test.ts", nodeSuite)).
			WithSource(typescripttest.TSFile("greeter.ts", greeter)).
			AssertTestsPass(t)
	})

	t.Run("a failing generated suite is reported", func(t *testing.T) {
		t.Parallel()
		failing := strings.Replace(nodeSuite, "'hello Roy'", "'goodbye Roy'", 1)
		s := probe(t)
		typescripttest.
			Of(typescripttest.TSFile("greeter.test.ts", failing)).
			WithSource(typescripttest.TSFile("greeter.ts", greeter)).
			AssertTestsPass(s)
		if s.skipped {
			t.Skip("no Node; the assertion itself was not exercised")
		}
		assertReports(t, s, "generated test suite failed")
	})

	t.Run("a run with no suite is reported rather than passing", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		typescripttest.Of(typescripttest.TSFile("user.gen.ts", primary)).AssertTestsPass(s)
		assertReports(t, s, "no test file")
	})

	t.Run("output the runner cannot execute names the runner", func(t *testing.T) {
		t.Parallel()
		// Node strips types rather than transforming them, so an enum
		// cannot run under it. That is the runner's limit rather than a
		// failing test, and the two call for different fixes.
		withEnum := `import { test } from 'node:test';
import { Role } from './role.ts';
test('reads the enum', () => { void Role.Admin; });
`
		s := probe(t)
		typescripttest.
			Of(typescripttest.TSFile("role.test.ts", withEnum)).
			WithSource(typescripttest.TSFile("role.ts",
				"export enum Role { Admin = 'admin' }\n")).
			AssertTestsPass(s)
		if s.skipped {
			t.Skip("no Node; the assertion itself was not exercised")
		}
		assertReports(t, s, "strips TypeScript types", "WithTestRunner")
	})

	t.Run("a declared runner is used instead", func(t *testing.T) {
		t.Parallel()
		// For output whose suite imports a framework, and for output
		// Node's type-stripping cannot execute.
		s := probe(t)
		typescripttest.
			Of(typescripttest.TSFile("a.test.ts", "export {};\n")).
			WithTestRunner("false").
			AssertTestsPass(s)
		assertReports(t, s, "generated test suite failed")
	})
}

func TestIsTestFile(t *testing.T) {
	t.Parallel()

	t.Run("both conventions are recognised", func(t *testing.T) {
		t.Parallel()
		// `.test.ts` is Node's and Jest's default, `.spec.ts` is
		// Angular's and Karma's. A harness recognising one would
		// silently have nothing to run for half the generators it
		// serves.
		for _, path := range []string{"a.test.ts", "a.spec.ts", "deep/a.test.ts"} {
			if !typescripttest.TSFile(path, "").IsTestFile() {
				t.Errorf("%s is not recognised as a test file", path)
			}
		}
		for _, path := range []string{"a.ts", "attest.ts", "a.test.d.ts"} {
			if typescripttest.TSFile(path, "").IsTestFile() {
				t.Errorf("%s is recognised as a test file", path)
			}
		}
	})
}

// suite parses the generated suite corpus.
func suite(t *testing.T) *typescripttest.Source {
	t.Helper()
	return typescripttest.Parse(t, typescripttest.TSFile("printer.test.ts", generatedSuite))
}
