// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package backend_test

import (
	"strings"
	"testing"

	"go.thesmos.sh/eidos/core/diag"
	"go.thesmos.sh/eidos/eidostest/backendtest"
	"go.thesmos.sh/eidos/eidostest/plugintest"
	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/lang/typescript"
	"go.thesmos.sh/eidos/lang/typescript/backend"
	"go.thesmos.sh/eidos/sink"
)

// target is the output file every fixture renders into.
var target = emit.Target{Dir: "out", Filename: "types.ts", ImportPath: "./out/types"}

// render drives the backend over one package and returns the file it
// wrote.
func render(t *testing.T, pkg *emit.Package) string {
	t.Helper()
	res := backendtest.Run(t, backendtest.RunOptions{
		Backend:      backend.New(),
		EmitPackages: []*emit.Package{pkg},
	})
	for _, d := range res.Diag.Diagnostics() {
		if d.Severity == diag.Error {
			t.Fatalf("unexpected error diagnostic: %s", d.Message)
		}
	}

	mem, ok := res.Sink.(*sink.Memory)
	if !ok {
		t.Fatalf("sink = %T, want *sink.Memory", res.Sink)
	}
	body, ok := mem.Get(target)
	if !ok {
		t.Fatalf("no file written for %s; wrote %d files", target.JoinPath(), mem.Len())
	}
	return string(body)
}

// pkgWith wraps decls in an emit package.
func pkgWith(decls ...emit.Node) *emit.Package {
	p := &emit.Package{Name: "out", Path: "./out"}
	for _, d := range decls {
		switch v := d.(type) {
		case *emit.Interface:
			p.Interfaces = append(p.Interfaces, v)
		case *emit.Struct:
			p.Structs = append(p.Structs, v)
		case *emit.Enum:
			p.Enums = append(p.Enums, v)
		case *emit.Alias:
			p.Aliases = append(p.Aliases, v)
		case *emit.Constant:
			p.Constants = append(p.Constants, v)
		case *emit.Variable:
			p.Variables = append(p.Variables, v)
		case *emit.Function:
			p.Functions = append(p.Functions, v)
		}
	}
	return p
}

func TestRenderInterface(t *testing.T) {
	t.Parallel()

	t.Run("renders properties as an interface", func(t *testing.T) {
		t.Parallel()
		got := render(t, pkgWith(&emit.Interface{
			Name:   "User",
			Target: target,
			Fields: []*emit.Field{
				{Name: "id", Type: emit.Builtin("string")},
				{Name: "age", Type: emit.Builtin("int")},
			},
		}))

		for _, want := range []string{
			"export interface User {",
			"id: string;",
			"age: number;",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("output missing %q:\n%s", want, got)
			}
		}
	})

	t.Run("carries the generated marker and nothing run-dependent", func(t *testing.T) {
		t.Parallel()
		// Two runs over one graph must produce identical bytes, so
		// there is no timestamp to differ.
		got := render(t, pkgWith(&emit.Interface{
			Name: "A", Target: target,
			Fields: []*emit.Field{{Name: "x", Type: emit.Builtin("string")}},
		}))

		if !strings.HasPrefix(got, "// Code generated by eidos. DO NOT EDIT.") {
			t.Errorf("missing generated marker:\n%s", got)
		}
		for _, forbidden := range []string{"Generated:", "20", "Command:"} {
			if strings.Contains(got, forbidden) {
				t.Errorf("output carries run-dependent text %q:\n%s", forbidden, got)
			}
		}
	})

	t.Run("output is byte-identical across runs", func(t *testing.T) {
		t.Parallel()
		build := func() string {
			return render(t, pkgWith(&emit.Interface{
				Name: "U", Target: target,
				Fields: []*emit.Field{
					{Name: "b", Type: emit.Builtin("string")},
					{Name: "a", Type: emit.Builtin("int")},
				},
			}))
		}
		if first, second := build(), build(); first != second {
			t.Fatalf("two runs differ:\n--- first ---\n%s\n--- second ---\n%s", first, second)
		}
	})
}

func TestRenderTypes(t *testing.T) {
	t.Parallel()

	// field renders one interface carrying a single typed property
	// and returns the property's line.
	field := func(t *testing.T, ref emit.Ref) string {
		t.Helper()
		got := render(t, pkgWith(&emit.Interface{
			Name: "T", Target: target,
			Fields: []*emit.Field{{Name: "v", Type: ref}},
		}))
		for l := range strings.SplitSeq(got, "\n") {
			if strings.HasPrefix(strings.TrimSpace(l), "v") {
				return strings.TrimSpace(l)
			}
		}
		t.Fatalf("no property line in:\n%s", got)
		return ""
	}

	t.Run("builtins map onto TypeScript spellings", func(t *testing.T) {
		t.Parallel()
		for name, want := range map[string]string{
			"string":  "v: string;",
			"bool":    "v: boolean;",
			"int":     "v: number;",
			"float64": "v: number;",
			"error":   "v: Error;",
		} {
			if got := field(t, emit.Builtin(name)); got != want {
				t.Errorf("builtin %q rendered %q, want %q", name, got, want)
			}
		}
	})

	t.Run("a slice renders as an array", func(t *testing.T) {
		t.Parallel()
		if got := field(t, emit.SliceOf(emit.Builtin("string"))); got != "v: string[];" {
			t.Fatalf("slice rendered %q", got)
		}
	})

	t.Run("a pointer renders as nullable", func(t *testing.T) {
		t.Parallel()
		// What a pointer carries that a value does not is the ability
		// to be absent, which TypeScript spells with null.
		if got := field(t, emit.Ptr(emit.Builtin("string"))); got != "v: string | null;" {
			t.Fatalf("pointer rendered %q", got)
		}
	})

	t.Run("a union element is parenthesised inside an array", func(t *testing.T) {
		t.Parallel()
		// `A | B[]` binds as `A | (B[])`, which is a different type.
		inner := emit.Union(
			emit.UnionTerm{Type: emit.Builtin("string")},
			emit.UnionTerm{Type: emit.Builtin("int")},
		)
		if got := field(t, emit.SliceOf(inner)); got != "v: (string | number)[];" {
			t.Fatalf("union array rendered %q", got)
		}
	})

	t.Run("a map renders as a Record", func(t *testing.T) {
		t.Parallel()
		ref := emit.MapOf(emit.Builtin("string"), emit.Builtin("int"))
		if got := field(t, ref); got != "v: Record<string, number>;" {
			t.Fatalf("map rendered %q", got)
		}
	})
}

func TestRenderEnumAndAlias(t *testing.T) {
	t.Parallel()

	t.Run("an enum renders its members with trailing commas", func(t *testing.T) {
		t.Parallel()
		got := render(t, pkgWith(&emit.Enum{
			Name: "Role", Target: target,
			Variants: []*emit.EnumVariant{
				{Name: "Admin", Value: emit.NewLiteralString("admin")},
				{Name: "Guest", Value: emit.NewLiteralString("guest")},
			},
		}))

		for _, want := range []string{
			"export enum Role {",
			"Admin = 'admin',",
			"Guest = 'guest',",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("output missing %q:\n%s", want, got)
			}
		}
	})

	t.Run("an alias renders as a type declaration", func(t *testing.T) {
		t.Parallel()
		got := render(t, pkgWith(&emit.Alias{
			Name: "ID", File: target, Target: emit.Builtin("string"),
		}))
		if !strings.Contains(got, "export type ID = string;") {
			t.Errorf("alias missing:\n%s", got)
		}
	})
}

func TestRenderDocs(t *testing.T) {
	t.Parallel()

	t.Run("a single doc line renders on one line", func(t *testing.T) {
		t.Parallel()
		iface := &emit.Interface{
			Name: "A", Target: target,
			Fields: []*emit.Field{{Name: "x", Type: emit.Builtin("string")}},
		}
		iface.DocLines = []string{"A thing."}

		got := render(t, pkgWith(iface))
		if !strings.Contains(got, "/** A thing. */") {
			t.Errorf("single-line doc not rendered as one line:\n%s", got)
		}
	})

	t.Run("several doc lines render as a JSDoc block", func(t *testing.T) {
		t.Parallel()
		// JSDoc rather than line comments: an editor surfaces a
		// `/** */` block on hover and ignores `//`.
		iface := &emit.Interface{
			Name: "A", Target: target,
			Fields: []*emit.Field{{Name: "x", Type: emit.Builtin("string")}},
		}
		iface.DocLines = []string{"First.", "", "Second."}

		got := render(t, pkgWith(iface))
		for _, want := range []string{"/**", " * First.", " *", " * Second.", " */"} {
			if !strings.Contains(got, want) {
				t.Errorf("JSDoc missing %q:\n%s", want, got)
			}
		}
	})
}

func TestExportedMarker(t *testing.T) {
	t.Parallel()

	t.Run("a declaration is exported unless it says otherwise", func(t *testing.T) {
		t.Parallel()
		// A generated type nothing can import is a type nothing can
		// use, so absence of the marker means exported.
		got := render(t, pkgWith(&emit.Interface{
			Name: "A", Target: target,
			Fields: []*emit.Field{{Name: "x", Type: emit.Builtin("string")}},
		}))
		if !strings.Contains(got, "export interface A") {
			t.Errorf("declaration not exported by default:\n%s", got)
		}
	})

	t.Run("an explicit false suppresses the keyword", func(t *testing.T) {
		t.Parallel()
		iface := &emit.Interface{
			Name: "Internal", Target: target,
			Fields: []*emit.Field{{Name: "x", Type: emit.Builtin("string")}},
		}
		typescript.MetaExported.Set(iface.EnsureMeta(), false, "test")

		got := render(t, pkgWith(iface))
		if strings.Contains(got, "export interface Internal") {
			t.Errorf("a non-exported declaration was exported:\n%s", got)
		}
		if !strings.Contains(got, "interface Internal") {
			t.Errorf("declaration missing entirely:\n%s", got)
		}
	})
}

// TestConformance runs the framework's plugin-conformance suite
// against this backend, plus the per-role byte-stability and
// diagnostic-discipline checks over representative emit fixtures —
// the deterministic-render contract byte-identical CI rebuilds and
// manifest hashing stand on.
func TestConformance(t *testing.T) {
	t.Parallel()

	t.Run("framework contracts", func(t *testing.T) {
		t.Parallel()
		plugintest.RunSuite(t, backend.New())
	})

	t.Run("backend contracts", func(t *testing.T) {
		t.Parallel()
		plugintest.RunBackendSuite(
			t,
			backend.New(),
			[]plugintest.BackendFixture{
				{
					Name: "one interface in one module",
					BuildEmitPackages: func(t *testing.T) []*emit.Package {
						t.Helper()
						return []*emit.Package{{
							Name: "demo",
							Path: "./demo",
							Interfaces: []*emit.Interface{{
								Name:    "User",
								Package: "demo",
								Fields: []*emit.Field{
									{Name: "id", Type: emit.Builtin("string")},
								},
								Target: emit.Target{
									Dir:      "demo",
									Filename: "user.gen.ts",
								},
							}},
						}}
					},
					Command: "test-fixture",
				},
				{
					Name: "every declaration kind in one module",
					BuildEmitPackages: func(t *testing.T) []*emit.Package {
						t.Helper()
						tgt := emit.Target{Dir: "demo", Filename: "all.gen.ts"}
						return []*emit.Package{{
							Name: "demo",
							Path: "./demo",
							Interfaces: []*emit.Interface{{
								Name: "I", Package: "demo", Target: tgt,
								Methods: []*emit.Method{{
									Name:    "get",
									Returns: []*emit.Return{{Type: emit.Builtin("string")}},
								}},
							}},
							Structs: []*emit.Struct{{
								Name: "C", Package: "demo", Target: tgt,
								Fields: []*emit.Field{{Name: "x", Type: emit.Builtin("int")}},
							}},
							Enums: []*emit.Enum{{
								Name: "E", Package: "demo", Target: tgt,
								Variants: []*emit.EnumVariant{{Name: "A"}},
							}},
							Aliases: []*emit.Alias{{
								Name: "T", File: tgt, Target: emit.Builtin("string"),
							}},
							Functions: []*emit.Function{{
								Name: "f", Package: "demo", Target: tgt,
							}},
							Constants: []*emit.Constant{{
								Name: "K", Package: "demo", Target: tgt,
								Type: emit.Builtin("int"), Value: emit.NewLiteralInt(1),
							}},
							Variables: []*emit.Variable{{
								Name: "v", Package: "demo", Target: tgt,
								Type: emit.Builtin("string"),
							}},
						}}
					},
					Command: "test-fixture",
				},
			},
		)
	})
}
