// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package backend

import (
	"strings"

	"go.thesmos.sh/eidos/emit"
)

// generatedMarker is the header line marking a file as machine-made.
//
// The wording matches Go's convention rather than inventing one:
// tooling across ecosystems greps for `Code generated .* DO NOT
// EDIT.`, and a linter configured to skip generated files finds this
// one without being told about eidos.
const generatedMarker = "// Code generated by eidos. DO NOT EDIT."

// header renders the file's opening lines.
//
// No timestamp and no input paths. Two runs over the same emit graph
// must produce byte-identical files, and a generated-at line is the
// one thing guaranteed to differ between them — which would make
// every regeneration a diff and every diff meaningless.
func header(_ emit.Target) string {
	return generatedMarker + "\n\n"
}

// footer renders the file's closing lines.
//
// Empty, for now, and separated from [header] so the two stay
// symmetric when a provenance line lands here. The Go backend's
// footer carries a hash over the body; this one has nowhere to put it
// yet because nothing reads it back.
func footer() string { return "" }

// finalise normalises a rendered file to the one canonical form.
//
// This stands where the Go backend calls format.Source. It cannot
// reject invalid output — see the package doc — so it does the half
// it can: collapse the blank-line runs a template's whitespace
// control leaves behind, strip trailing whitespace, and end the file
// with exactly one newline.
//
// Everything else is the templates' job. A normaliser that reflowed
// declarations would be a printer, and a printer is the largest
// component this package could acquire.
func finalise(body string) []byte {
	lines := strings.Split(body, "\n")
	out := make([]string, 0, len(lines))

	blank := 0
	for _, l := range lines {
		l = strings.TrimRight(l, " \t")
		if l == "" {
			blank++
			// One blank line separates declarations; two or more are
			// an artefact of template whitespace control rather than
			// anything a template meant to say.
			if blank > 1 {
				continue
			}
			out = append(out, l)
			continue
		}
		blank = 0
		out = append(out, l)
	}

	joined := strings.TrimRight(strings.Join(out, "\n"), "\n")
	if joined == "" {
		return nil
	}
	return []byte(joined + "\n")
}
