// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golang

import (
	"regexp"
	"strings"

	"go.thesmos.sh/eidos/core/naming"
	"go.thesmos.sh/eidos/node"
)

// Go's naming and file conventions — the ones a generator has to
// follow for its output to be recognised by the toolchain and by a
// reader.
//
// Some of these are enforced by the toolchain and getting them
// wrong is a build failure: a test function whose name does not
// start with `Test` never runs, and a generated-file header in the
// wrong form is invisible to every tool that skips generated code.
// The rest are conventions a reader relies on, where a generator
// inventing its own produces output that works and reads as
// foreign.

// generatedPattern is the form `go generate` documents and every
// tool that skips generated files matches against.
//
// Anchored and exact: the line must start the file's comment, the
// spacing is fixed, and the trailer is `DO NOT EDIT.` with the
// full stop. A header that differs in any of those is not a
// generated-file marker to gopls, to golangci-lint's `generated`
// filter, or to a coverage tool — the file is treated as
// hand-written and its findings are reported to an author who
// cannot act on them.
//
//nolint:gochecknoglobals // compiled once; the pattern is a constant
var generatedPattern = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// GeneratedHeader returns the canonical generated-file marker.
//
//	// Code generated by <tool>. DO NOT EDIT.
//
// The exact spelling matters — see [generatedPattern] for what
// consumes it.
func GeneratedHeader(tool string) string {
	if tool == "" {
		tool = "eidos"
	}
	return "// Code generated by " + tool + ". DO NOT EDIT."
}

// IsGeneratedSource reports whether a line is the canonical
// generated-file marker.
//
// Takes a line rather than a whole file because the marker may
// appear anywhere before the package clause — after a licence
// header, typically — and a caller scanning that prefix knows where
// it is looking.
func IsGeneratedSource(line string) bool {
	return generatedPattern.MatchString(strings.TrimRight(line, "\r\n"))
}

// BuildTag renders a `//go:build` constraint line.
//
// The modern form only. The paired `// +build` line was required
// before Go 1.17 and is now noise the toolchain regenerates; a
// generator emitting one produces a file `gofmt` immediately
// rewrites, which makes its output unstable against the formatter.
func BuildTag(expr string) string {
	if expr == "" {
		return ""
	}
	return "//go:build " + expr
}

// Test function prefixes the toolchain recognises. A function whose
// name does not begin with one of these is not run, whatever its
// signature — which is a generated test that silently never
// executes.
const (
	TestPrefix      = "Test"
	BenchmarkPrefix = "Benchmark"
	FuzzPrefix      = "Fuzz"
	ExamplePrefix   = "Example"
)

// TestFuncName composes a test function's identifier from its
// subject and the behaviour under test.
//
// Both parts are Pascal-cased and concatenated, because the
// toolchain requires the character after the prefix to be
// upper-case or non-letter: `Testfoo` is not a test, and the
// difference is invisible until the suite reports one fewer case
// than the file declares.
//
// An empty behaviour yields `Test<Subject>`, which is the whole-
// subject case.
func TestFuncName(subject, behaviour string) string {
	return TestPrefix + naming.Pascal(subject) + naming.Pascal(behaviour)
}

// BenchmarkFuncName composes a benchmark function's identifier.
func BenchmarkFuncName(subject, behaviour string) string {
	return BenchmarkPrefix + naming.Pascal(subject) + naming.Pascal(behaviour)
}

// FuzzFuncName composes a fuzz target's identifier.
func FuzzFuncName(subject string) string {
	return FuzzPrefix + naming.Pascal(subject)
}

// ExampleFuncName composes an example's identifier.
//
// The toolchain binds an example to the symbol it documents by
// name: `ExampleStore` documents `Store`, `ExampleStore_Get`
// documents its Get method, and the underscore is the separator
// that makes the association. An example whose name matches no
// symbol is rejected by `go vet` rather than ignored.
func ExampleFuncName(subject, method string) string {
	if method == "" {
		return ExamplePrefix + subject
	}
	return ExamplePrefix + subject + "_" + method
}

// ConstructorName composes the conventional constructor identifier
// — `New<Type>`.
//
// Bare `New` where the type name is empty, which is the
// one-type-per-package convention Go's own libraries follow.
func ConstructorName(typeName string) string {
	return "New" + naming.Pascal(typeName)
}

// GetterName composes the conventional accessor identifier.
//
// The field's own exported name, without a `Get` prefix: Go's style
// guidance is explicit that `Get` is not idiomatic on an accessor,
// and generated code that uses it reads as translated from another
// language.
func GetterName(field string) string { return naming.Pascal(field) }

// SetterName composes the conventional mutator identifier —
// `Set<Field>`.
//
// `Set` is idiomatic where `Get` is not, because the verb
// distinguishes the call from the field it writes.
func SetterName(field string) string { return "Set" + naming.Pascal(field) }

// WithName composes the fluent-option identifier — `With<Field>`.
func WithName(field string) string { return "With" + naming.Pascal(field) }

// SentinelName composes an error variable's identifier —
// `Err<Subject>`.
//
// The convention every Go codebase follows and the one a sentinel
// detector matches on, so a generator emitting an error variable
// under any other name produces one nothing finds.
func SentinelName(subject string) string { return "Err" + naming.Pascal(subject) }

// ParseFuncName composes a parse function's identifier —
// `Parse<Type>`.
func ParseFuncName(typeName string) string { return "Parse" + naming.Pascal(typeName) }

// Doc renders a doc comment that satisfies godoc's opening
// convention.
//
// The comment must begin with the symbol's own name, which is what
// lets a reader searching for a symbol find its documentation and
// what `revive` and `staticcheck` check for. A text already opening
// with the name is left alone, so a caller writing the whole
// sentence is not double-prefixed.
//
// Returns the empty string for empty text: a symbol with nothing to
// say is better undocumented than documented with its own name and
// a full stop.
func Doc(name, text string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	if strings.HasPrefix(text, name) {
		return text
	}
	return name + " " + text
}

// DeprecatedDoc renders the deprecation marker tooling recognises.
//
//	Deprecated: <reason>
//
// The exact form matters: gopls, staticcheck and pkg.go.dev all
// match on this prefix at the start of a paragraph, and a
// differently-worded note is prose nothing acts on. It belongs in
// its own paragraph, which is the caller's to arrange.
func DeprecatedDoc(reason string) string {
	reason = strings.TrimSpace(reason)
	if reason == "" {
		return "Deprecated: this symbol is deprecated."
	}
	return "Deprecated: " + reason
}

// TestFileName returns the test-file name for a source basename.
//
// The `_test.go` ending is what confines the file to test builds
// and what triggers the framework's external-test-package shift, so
// a generator naming its output anything else produces a file that
// ships in the consumer's binary.
func TestFileName(base string) string {
	base = strings.TrimSuffix(base, ".go")
	if strings.HasSuffix(base, "_test") {
		return base + ".go"
	}
	return base + "_test.go"
}

// IsTestFileName reports whether a filename lands in the test
// build.
func IsTestFileName(name string) bool {
	return strings.HasSuffix(strings.TrimSuffix(name, ".go"), "_test")
}

// DocSummary returns a doc comment's first sentence — what godoc
// shows in a package index and what a generated doc comment should
// carry forward when it derives from an existing one.
//
// Ends at the first full stop followed by a space or the end of the
// text, which is godoc's own rule. An abbreviation mid-sentence
// therefore truncates early; that is godoc's behaviour too, and
// matching it is worth more than being cleverer than the tool the
// output is read through.
//
// Returns the whole text when it holds no sentence break, and the
// empty string for empty input.
func DocSummary(text string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	for i := 0; i < len(text); i++ {
		if text[i] != '.' {
			continue
		}
		if i+1 == len(text) {
			return text
		}
		if text[i+1] == ' ' || text[i+1] == '\n' || text[i+1] == '\t' {
			return text[:i+1]
		}
	}
	return text
}

// DocDeprecation returns the reason a doc comment's deprecation
// marker gives, and whether the comment carries one.
//
// Matched on the exact prefix gopls, staticcheck and pkg.go.dev
// consult, at the start of a line — a mention of the word elsewhere
// in the prose is discussion, not a marker, and treating it as one
// would report every comment explaining why something is *not*
// deprecated.
func DocDeprecation(text string) (reason string, deprecated bool) {
	const marker = "Deprecated: "
	for line := range strings.SplitSeq(text, "\n") {
		trimmed := strings.TrimSpace(line)
		if after, found := strings.CutPrefix(trimmed, marker); found {
			return strings.TrimSpace(after), true
		}
	}
	return "", false
}

// JSONName returns the identifier a field serialises under and
// whether it is serialised at all.
//
// Go's encoding/json rule, which every codec that reads the tag
// follows: `json:"-"` excludes the field, a leading name overrides
// the identifier, an empty name keeps it, and options after the
// first comma are not part of the name.
//
// The exclusion is the case worth having: `json:"-"` and
// `json:"-,"` differ — the second names a field literally called
// `-` — and a caller splitting on the comma without checking gets
// them backwards.
func JSONName(f *node.Field) (name string, serialised bool) {
	if f == nil || f.Name == "" {
		return "", false
	}
	raw, tagged := TagValue(f.Tag, "json")
	if !tagged {
		return f.Name, true
	}
	if raw == "-" {
		return "", false
	}
	declared, _, _ := strings.Cut(raw, ",")
	if declared == "" {
		return f.Name, true
	}
	return declared, true
}

// HasTagOption reports whether a field's tag carries the named
// option — `omitempty`, `string`, `omitzero`.
//
// The options follow the name after a comma, so a caller checking
// for one by substring matches a field literally named `omitempty`
// as well.
func HasTagOption(f *node.Field, key, option string) bool {
	if f == nil {
		return false
	}
	raw, tagged := TagValue(f.Tag, key)
	if !tagged {
		return false
	}
	_, opts, found := strings.Cut(raw, ",")
	if !found {
		return false
	}
	for opt := range strings.SplitSeq(opts, ",") {
		if opt == option {
			return true
		}
	}
	return false
}
