// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golang_test

import (
	"strings"
	"testing"

	"go.thesmos.sh/eidos/lang/golang"
	"go.thesmos.sh/eidos/node"
)

func TestGeneratedHeader(t *testing.T) {
	t.Parallel()

	t.Run("renders the canonical marker", func(t *testing.T) {
		t.Parallel()
		got := golang.GeneratedHeader("eidos")
		if got != "// Code generated by eidos. DO NOT EDIT." {
			t.Fatalf("GeneratedHeader = %q", got)
		}
	})

	t.Run("the header it writes is the header it recognises", func(t *testing.T) {
		t.Parallel()
		// The round trip is the whole contract: a header that differs
		// in spacing or punctuation is not a generated-file marker to
		// gopls, to the lint `generated` filter, or to coverage — the
		// file is treated as hand-written and its findings reach an
		// author who cannot act on them.
		if !golang.IsGeneratedSource(golang.GeneratedHeader("testkit")) {
			t.Fatalf("GeneratedHeader must satisfy IsGeneratedSource")
		}
	})

	t.Run("a near-miss is not a marker", func(t *testing.T) {
		t.Parallel()
		for _, line := range []string{
			"// Code generated by eidos. DO NOT EDIT",  // no full stop
			"// code generated by eidos. DO NOT EDIT.", // lower case
			"//Code generated by eidos. DO NOT EDIT.",  // no space
			"// Generated by eidos. DO NOT EDIT.",      // wrong opening
			"  // Code generated by x. DO NOT EDIT.",   // indented
		} {
			if golang.IsGeneratedSource(line) {
				t.Errorf("IsGeneratedSource(%q) = true", line)
			}
		}
	})

	t.Run("tolerates a trailing newline", func(t *testing.T) {
		t.Parallel()
		// Callers scan a file's leading lines, which carry theirs.
		if !golang.IsGeneratedSource(golang.GeneratedHeader("x") + "\n") {
			t.Fatalf("a trailing newline must not defeat the match")
		}
	})

	t.Run("an unnamed tool still produces a valid marker", func(t *testing.T) {
		t.Parallel()
		if !golang.IsGeneratedSource(golang.GeneratedHeader("")) {
			t.Fatalf("an empty tool name must still yield a valid marker")
		}
	})
}

func TestBuildTag(t *testing.T) {
	t.Parallel()

	t.Run("renders the modern form only", func(t *testing.T) {
		t.Parallel()
		// The paired `// +build` line is now noise the toolchain
		// regenerates; emitting one produces a file gofmt rewrites,
		// which makes the output unstable against the formatter.
		got := golang.BuildTag("integration")
		if got != "//go:build integration" {
			t.Fatalf("BuildTag = %q", got)
		}
		if strings.Contains(got, "+build") {
			t.Fatalf("BuildTag must not emit the legacy line")
		}
	})

	t.Run("an empty constraint renders nothing", func(t *testing.T) {
		t.Parallel()
		if got := golang.BuildTag(""); got != "" {
			t.Fatalf("BuildTag(\"\") = %q", got)
		}
	})
}

func TestTestFuncNames(t *testing.T) {
	t.Parallel()

	t.Run("the character after the prefix is upper-case", func(t *testing.T) {
		t.Parallel()
		// The toolchain requires it: `Testfoo` is not a test, and the
		// difference is invisible until the suite reports one fewer
		// case than the file declares.
		got := golang.TestFuncName("store", "records a call")
		if !strings.HasPrefix(got, "Test") || got[4] < 'A' || got[4] > 'Z' {
			t.Fatalf("TestFuncName = %q, want an upper-case fifth rune", got)
		}
	})

	t.Run("an empty behaviour names the whole subject", func(t *testing.T) {
		t.Parallel()
		if got := golang.TestFuncName("Store", ""); got != "TestStore" {
			t.Fatalf("TestFuncName = %q, want TestStore", got)
		}
	})

	t.Run("benchmark and fuzz take their own prefixes", func(t *testing.T) {
		t.Parallel()
		if got := golang.BenchmarkFuncName("Store", "Get"); got != "BenchmarkStoreGet" {
			t.Fatalf("BenchmarkFuncName = %q", got)
		}
		if got := golang.FuzzFuncName("Parse"); got != "FuzzParse" {
			t.Fatalf("FuzzFuncName = %q", got)
		}
	})

	t.Run("an example binds to its symbol by name", func(t *testing.T) {
		t.Parallel()
		// The toolchain associates an example with the symbol it
		// documents, and `go vet` rejects one matching nothing.
		if got := golang.ExampleFuncName("Store", ""); got != "ExampleStore" {
			t.Fatalf("ExampleFuncName = %q", got)
		}
		if got := golang.ExampleFuncName("Store", "Get"); got != "ExampleStore_Get" {
			t.Fatalf("ExampleFuncName = %q, want the underscore separator", got)
		}
	})
}

func TestExportedName(t *testing.T) {
	t.Parallel()

	t.Run("exports an unexported identifier", func(t *testing.T) {
		t.Parallel()
		if got := golang.ExportedName("value"); got != "Value" {
			t.Fatalf("ExportedName = %q, want Value", got)
		}
	})

	t.Run("preserves initialisms", func(t *testing.T) {
		t.Parallel()
		// The reason a generator must not hand-roll this: upper-casing
		// the first rune yields `Url_path`, and title-casing per word
		// yields `UrlPath`. Both compile and both read as foreign in a
		// file beside hand-written Go.
		if got := golang.ExportedName("url_path"); got != "URLPath" {
			t.Fatalf("ExportedName = %q, want URLPath", got)
		}
	})

	t.Run("an already-exported identifier is unchanged", func(t *testing.T) {
		t.Parallel()
		// Source field names arrive exported more often than not, and a
		// generator applies this unconditionally. A conversion that was
		// not idempotent would rewrite `URLPath` to `UrlPath` on the
		// way through and break the correspondence to the source.
		for _, name := range []string{"URLPath", "Value", "Result0"} {
			if got := golang.ExportedName(name); got != name {
				t.Fatalf("ExportedName(%q) = %q, want unchanged", name, got)
			}
		}
	})

	t.Run("empty input yields empty", func(t *testing.T) {
		t.Parallel()
		// No fallback is invented here: a slot with no derivable name
		// is the caller's problem, and stubgen's positional `Result0`
		// is one answer among several.
		if got := golang.ExportedName(""); got != "" {
			t.Fatalf("ExportedName(%q) = %q, want empty", "", got)
		}
	})

	t.Run("converts case and nothing else", func(t *testing.T) {
		t.Parallel()
		// Documented explicitly because the result is not guaranteed to
		// be a legal identifier: an illegal rune survives, and a
		// digit-leading name cannot be exported at all. A caller with
		// untrusted input sanitises first.
		if got := golang.ExportedName("foo$bar"); got != "Foo$bar" {
			t.Fatalf("ExportedName = %q, want the illegal rune preserved", got)
		}
		if got := golang.ExportedName("2fast"); got != "2fast" {
			t.Fatalf("ExportedName = %q, want the digit-leading name unchanged", got)
		}
		if got := golang.ExportedName(golang.SafeIdent("foo$bar")); got != "FooBar" {
			t.Fatalf("ExportedName(SafeIdent(...)) = %q, want FooBar", got)
		}
	})

	t.Run("the convention wrappers are built on it", func(t *testing.T) {
		t.Parallel()
		// The general case and the specific wrappers must not fork:
		// one of them regressing to a naive upper-casing would give a
		// generator two spellings of the same field.
		const field = "url_path"
		exported := golang.ExportedName(field)
		if got := golang.GetterName(field); got != exported {
			t.Fatalf("GetterName = %q, want %q", got, exported)
		}
		if got := golang.SetterName(field); got != "Set"+exported {
			t.Fatalf("SetterName = %q, want Set%s", got, exported)
		}
		if got := golang.WithName(field); got != "With"+exported {
			t.Fatalf("WithName = %q, want With%s", got, exported)
		}
		if got := golang.SentinelName(field); got != "Err"+exported {
			t.Fatalf("SentinelName = %q, want Err%s", got, exported)
		}
		if got := golang.ParseFuncName(field); got != "Parse"+exported {
			t.Fatalf("ParseFuncName = %q, want Parse%s", got, exported)
		}
		if got := golang.ConstructorName(field); got != "New"+exported {
			t.Fatalf("ConstructorName = %q, want New%s", got, exported)
		}
	})
}

func TestIdentifierConventions(t *testing.T) {
	t.Parallel()

	t.Run("a constructor is New<Type>", func(t *testing.T) {
		t.Parallel()
		if got := golang.ConstructorName("Store"); got != "NewStore" {
			t.Fatalf("ConstructorName = %q", got)
		}
	})

	t.Run("an accessor carries no Get prefix", func(t *testing.T) {
		t.Parallel()
		// Go's style guidance is explicit that `Get` is not idiomatic
		// on an accessor; code using it reads as translated from
		// another language.
		if got := golang.GetterName("name"); got != "Name" {
			t.Fatalf("GetterName = %q, want Name", got)
		}
	})

	t.Run("a mutator does carry Set", func(t *testing.T) {
		t.Parallel()
		// The verb distinguishes the call from the field it writes.
		if got := golang.SetterName("name"); got != "SetName" {
			t.Fatalf("SetterName = %q", got)
		}
	})

	t.Run("an option is With<Field>", func(t *testing.T) {
		t.Parallel()
		if got := golang.WithName("timeout"); got != "WithTimeout" {
			t.Fatalf("WithName = %q", got)
		}
	})

	t.Run("a sentinel is Err<Subject>", func(t *testing.T) {
		t.Parallel()
		// The convention a sentinel detector matches on, so a variable
		// under any other name is one nothing finds.
		if got := golang.SentinelName("not found"); got != "ErrNotFound" {
			t.Fatalf("SentinelName = %q", got)
		}
	})

	t.Run("a parse function is Parse<Type>", func(t *testing.T) {
		t.Parallel()
		if got := golang.ParseFuncName("Status"); got != "ParseStatus" {
			t.Fatalf("ParseFuncName = %q", got)
		}
	})
}

func TestDoc(t *testing.T) {
	t.Parallel()

	t.Run("opens with the symbol's own name", func(t *testing.T) {
		t.Parallel()
		// What lets a reader searching for a symbol find its
		// documentation, and what revive and staticcheck check for.
		if got := golang.Doc("Get", "returns the stored value."); got != "Get returns the stored value." {
			t.Fatalf("Doc = %q", got)
		}
	})

	t.Run("text already opening with the name is left alone", func(t *testing.T) {
		t.Parallel()
		got := golang.Doc("Get", "Get returns the stored value.")
		if got != "Get returns the stored value." {
			t.Fatalf("Doc = %q, want no double prefix", got)
		}
	})

	t.Run("empty text stays empty", func(t *testing.T) {
		t.Parallel()
		// A symbol with nothing to say is better undocumented than
		// documented with its own name and a full stop.
		if got := golang.Doc("Get", "   "); got != "" {
			t.Fatalf("Doc = %q, want empty", got)
		}
	})

	t.Run("the deprecation marker takes the exact recognised form", func(t *testing.T) {
		t.Parallel()
		// gopls, staticcheck and pkg.go.dev all match on this prefix;
		// a differently-worded note is prose nothing acts on.
		got := golang.DeprecatedDoc("use Fetch instead.")
		if !strings.HasPrefix(got, "Deprecated: ") {
			t.Fatalf("DeprecatedDoc = %q", got)
		}
	})

	t.Run("a reasonless deprecation still marks", func(t *testing.T) {
		t.Parallel()
		if !strings.HasPrefix(golang.DeprecatedDoc(""), "Deprecated: ") {
			t.Fatalf("an empty reason must still produce the marker")
		}
	})
}

func TestTestFileName(t *testing.T) {
	t.Parallel()

	t.Run("appends the test ending", func(t *testing.T) {
		t.Parallel()
		// The ending is what confines the file to test builds; a
		// generator naming its output anything else ships it in the
		// consumer's binary.
		if got := golang.TestFileName("store.go"); got != "store_test.go" {
			t.Fatalf("TestFileName = %q", got)
		}
	})

	t.Run("takes a basename with or without the extension", func(t *testing.T) {
		t.Parallel()
		if got := golang.TestFileName("store"); got != "store_test.go" {
			t.Fatalf("TestFileName = %q", got)
		}
	})

	t.Run("appending twice is a no-op", func(t *testing.T) {
		t.Parallel()
		if got := golang.TestFileName("store_test.go"); got != "store_test.go" {
			t.Fatalf("TestFileName = %q, want no doubled suffix", got)
		}
	})

	t.Run("recognises a test filename", func(t *testing.T) {
		t.Parallel()
		if !golang.IsTestFileName("store_test.go") || golang.IsTestFileName("store.go") {
			t.Fatalf("IsTestFileName must match exactly the test ending")
		}
	})
}

func TestDocSummary(t *testing.T) {
	t.Parallel()

	t.Run("takes the first sentence", func(t *testing.T) {
		t.Parallel()
		// What godoc shows in a package index, and what a derived doc
		// comment should carry forward.
		got := golang.DocSummary("Get returns the value. It blocks until ready.")
		if got != "Get returns the value." {
			t.Fatalf("DocSummary = %q", got)
		}
	})

	t.Run("a text with no break is its own summary", func(t *testing.T) {
		t.Parallel()
		if got := golang.DocSummary("Get returns the value"); got != "Get returns the value" {
			t.Fatalf("DocSummary = %q", got)
		}
	})

	t.Run("a trailing full stop ends the sentence", func(t *testing.T) {
		t.Parallel()
		if got := golang.DocSummary("Get returns the value."); got != "Get returns the value." {
			t.Fatalf("DocSummary = %q", got)
		}
	})

	t.Run("breaks at a newline as godoc does", func(t *testing.T) {
		t.Parallel()
		got := golang.DocSummary("Get returns the value.\nMore prose.")
		if got != "Get returns the value." {
			t.Fatalf("DocSummary = %q", got)
		}
	})

	t.Run("empty text has no summary", func(t *testing.T) {
		t.Parallel()
		if got := golang.DocSummary("  "); got != "" {
			t.Fatalf("DocSummary = %q", got)
		}
	})
}

func TestDocDeprecation(t *testing.T) {
	t.Parallel()

	t.Run("reads the reason off the marker line", func(t *testing.T) {
		t.Parallel()
		reason, dep := golang.DocDeprecation("Get returns the value.\n\nDeprecated: use Fetch.")
		if !dep || reason != "use Fetch." {
			t.Fatalf("DocDeprecation = %q, %v", reason, dep)
		}
	})

	t.Run("a mention in prose is not a marker", func(t *testing.T) {
		t.Parallel()
		// Treating it as one would report every comment explaining why
		// something is not deprecated.
		_, dep := golang.DocDeprecation("This is not Deprecated: it is current.")
		if dep {
			t.Fatalf("a mid-line mention must not read as a marker")
		}
	})

	t.Run("a comment with no marker reports none", func(t *testing.T) {
		t.Parallel()
		if _, dep := golang.DocDeprecation("Get returns the value."); dep {
			t.Fatalf("DocDeprecation found a marker where none is written")
		}
	})

	t.Run("what DeprecatedDoc writes, DocDeprecation reads", func(t *testing.T) {
		t.Parallel()
		reason, dep := golang.DocDeprecation(golang.DeprecatedDoc("use Fetch."))
		if !dep || reason != "use Fetch." {
			t.Fatalf("round trip = %q, %v", reason, dep)
		}
	})
}

func TestJSONName(t *testing.T) {
	t.Parallel()

	tagged := func(tag string) *node.Field {
		return &node.Field{Name: "UserID", Type: builtinRef("string"), Tag: tag}
	}

	t.Run("an untagged field serialises under its identifier", func(t *testing.T) {
		t.Parallel()
		name, ok := golang.JSONName(tagged(""))
		if !ok || name != "UserID" {
			t.Fatalf("JSONName = %q, %v", name, ok)
		}
	})

	t.Run("a declared name overrides the identifier", func(t *testing.T) {
		t.Parallel()
		name, ok := golang.JSONName(tagged("`json:\"user_id\"`"))
		if !ok || name != "user_id" {
			t.Fatalf("JSONName = %q, %v", name, ok)
		}
	})

	t.Run("options are not part of the name", func(t *testing.T) {
		t.Parallel()
		name, _ := golang.JSONName(tagged("`json:\"user_id,omitempty\"`"))
		if name != "user_id" {
			t.Fatalf("JSONName = %q", name)
		}
	})

	t.Run("an empty name keeps the identifier", func(t *testing.T) {
		t.Parallel()
		name, ok := golang.JSONName(tagged("`json:\",omitempty\"`"))
		if !ok || name != "UserID" {
			t.Fatalf("JSONName = %q, %v", name, ok)
		}
	})

	t.Run("a dash excludes the field", func(t *testing.T) {
		t.Parallel()
		if _, ok := golang.JSONName(tagged("`json:\"-\"`")); ok {
			t.Fatalf("json:\"-\" must exclude the field")
		}
	})

	t.Run("a dash with a comma names a field called dash", func(t *testing.T) {
		t.Parallel()
		// The case a caller splitting on the comma without checking
		// gets backwards.
		name, ok := golang.JSONName(tagged("`json:\"-,\"`"))
		if !ok || name != "-" {
			t.Fatalf("JSONName = %q, %v; want the literal dash", name, ok)
		}
	})

	t.Run("a nil field serialises nothing", func(t *testing.T) {
		t.Parallel()
		if _, ok := golang.JSONName(nil); ok {
			t.Fatalf("JSONName(nil) reported a serialised field")
		}
	})
}

func TestHasTagOption(t *testing.T) {
	t.Parallel()

	t.Run("finds an option after the name", func(t *testing.T) {
		t.Parallel()
		f := &node.Field{Name: "N", Tag: "`json:\"n,omitempty,string\"`"}
		if !golang.HasTagOption(f, "json", "omitempty") {
			t.Fatalf("HasTagOption(omitempty) = false")
		}
		if !golang.HasTagOption(f, "json", "string") {
			t.Fatalf("HasTagOption(string) = false")
		}
	})

	t.Run("a field named for the option is not carrying it", func(t *testing.T) {
		t.Parallel()
		// A substring check would match this.
		f := &node.Field{Name: "N", Tag: "`json:\"omitempty\"`"}
		if golang.HasTagOption(f, "json", "omitempty") {
			t.Fatalf("a field named omitempty must not read as carrying the option")
		}
	})

	t.Run("an absent key carries no options", func(t *testing.T) {
		t.Parallel()
		f := &node.Field{Name: "N", Tag: "`db:\"n,omitempty\"`"}
		if golang.HasTagOption(f, "json", "omitempty") {
			t.Fatalf("HasTagOption read an option off another key")
		}
		if golang.HasTagOption(nil, "json", "omitempty") {
			t.Fatalf("HasTagOption(nil) = true")
		}
	})
}

func TestHasTagOptionEdges(t *testing.T) {
	t.Parallel()

	t.Run("a tag with a name and no options carries none", func(t *testing.T) {
		t.Parallel()
		f := &node.Field{Name: "N", Tag: "`json:\"n\"`"}
		if golang.HasTagOption(f, "json", "omitempty") {
			t.Fatalf("HasTagOption = true for a tag with no options")
		}
	})
}

// TestIsSentinelName pins the matcher half of [golang.SentinelName].
//
// The pair has to agree: a generator composing a name with one rule
// and finding it with another emits variables its own detector cannot
// see, and nothing fails until a consumer notices the sentinel it
// declared was ignored.
func TestIsSentinelName(t *testing.T) {
	t.Parallel()

	t.Run("matches what SentinelName composes", func(t *testing.T) {
		t.Parallel()
		for _, subject := range []string{"NotFound", "conflict", "Timeout"} {
			if got := golang.SentinelName(subject); !golang.IsSentinelName(got) {
				t.Errorf("SentinelName(%q) = %q, which IsSentinelName rejects", subject, got)
			}
		}
	})

	t.Run("Err alone is not a sentinel name", func(t *testing.T) {
		t.Parallel()
		// It carries the prefix and no subject, so it names nothing in
		// particular; admitting it would classify a package's generic
		// error variable as a sentinel for a type.
		if golang.IsSentinelName("Err") {
			t.Errorf("bare Err must not match")
		}
	})

	t.Run("rejects names that are not sentinels", func(t *testing.T) {
		t.Parallel()
		for _, ident := range []string{"", "NotFound", "errNotFound", "Errors", "Erro"} {
			if golang.IsSentinelName(ident) {
				t.Errorf("IsSentinelName(%q) = true, want false", ident)
			}
		}
	})
}

// TestSentinelSubject pins the third side of a pair that was two, and
// the round trip that makes the three one rule.
func TestSentinelSubject(t *testing.T) {
	t.Parallel()

	t.Run("strips the prefix from a sentinel", func(t *testing.T) {
		t.Parallel()
		subject, prefixed := golang.SentinelSubject("ErrNotFound")
		if !prefixed || subject != "NotFound" {
			t.Fatalf("SentinelSubject = %q, %v; want NotFound, true", subject, prefixed)
		}
	})

	t.Run("round-trips against SentinelName", func(t *testing.T) {
		t.Parallel()
		// The property the three symbols exist to hold. Composed by one
		// rule and decomposed by another, a generator emits variables
		// its own detector cannot see.
		for _, subject := range []string{"gone", "NotFound", "url_path", "Conflict"} {
			name := golang.SentinelName(subject)
			back, prefixed := golang.SentinelSubject(name)
			if !prefixed || golang.SentinelName(back) != name {
				t.Fatalf("SentinelName(%q) = %q, back to %q (%v) — round trip broken",
					subject, name, back, prefixed)
			}
		}
	})

	t.Run("a name that merely starts with Err is returned whole", func(t *testing.T) {
		t.Parallel()
		// TrimPrefix turns Errors into ors, which is a valid identifier
		// and therefore compiles — with a subject the author never
		// wrote in every message that interpolates it.
		subject, prefixed := golang.SentinelSubject("Errors")
		if prefixed || subject != "Errors" {
			t.Fatalf("SentinelSubject(Errors) = %q, %v; want Errors, false", subject, prefixed)
		}
	})

	t.Run("bare Err carries no subject", func(t *testing.T) {
		t.Parallel()
		// TrimPrefix yields the empty string here, which renders as
		// nothing at all wherever the subject is interpolated.
		subject, prefixed := golang.SentinelSubject("Err")
		if prefixed || subject != "Err" {
			t.Fatalf("SentinelSubject(Err) = %q, %v; want Err, false", subject, prefixed)
		}
	})

	t.Run("an unexported error variable is not a sentinel", func(t *testing.T) {
		t.Parallel()
		// SentinelName cannot compose one, so reporting a subject for
		// it would claim a round trip that does not hold.
		subject, prefixed := golang.SentinelSubject("errNotFound")
		if prefixed || subject != "errNotFound" {
			t.Fatalf("SentinelSubject(errNotFound) = %q, %v; want it returned whole", subject, prefixed)
		}
	})

	t.Run("agrees with IsSentinelName on every input", func(t *testing.T) {
		t.Parallel()
		// One rule, three symbols. A disagreement here is a name one
		// half classifies as a sentinel and the other decomposes as
		// though it were not.
		for _, ident := range []string{"ErrNotFound", "Errors", "Err", "errNotFound", "", "Err_"} {
			_, prefixed := golang.SentinelSubject(ident)
			if prefixed != golang.IsSentinelName(ident) {
				t.Fatalf("SentinelSubject(%q) prefixed=%v but IsSentinelName=%v",
					ident, prefixed, golang.IsSentinelName(ident))
			}
		}
	})
}

// TestHasTagOption_Absent pins the miss. A tag that is present but
// carries a different option must read as absent, or a generator emits
// the behaviour the author spelled off.
func TestHasTagOption_Absent(t *testing.T) {
	t.Parallel()

	t.Run("an option the tag does not carry reads false", func(t *testing.T) {
		t.Parallel()
		f := &node.Field{Name: "ID", Type: builtinRef("string"), Tag: `json:"id,omitempty"`}
		if golang.HasTagOption(f, "json", "string") {
			t.Error("an option absent from the tag reported present")
		}
	})

	t.Run("an option the tag does carry still reads true", func(t *testing.T) {
		t.Parallel()
		f := &node.Field{Name: "ID", Type: builtinRef("string"), Tag: `json:"id,omitempty"`}
		if !golang.HasTagOption(f, "json", "omitempty") {
			t.Error("an option present in the tag reported absent")
		}
	})
}

// A docblock naming a derived identifier wraps after the substitution,
// not before it.
//
// The defect: a template wrapping its own prose has to guess the
// identifier's length while writing it, and the guess is wrong for
// every declaration of a different name. A builder for `Comment` left
// one line short and one at 86 columns, and gofmt rewraps neither.
func TestWrapDoc(t *testing.T) {
	t.Parallel()

	t.Run("no line exceeds the width", func(t *testing.T) {
		t.Parallel()
		got := golang.WrapDoc(
			"CommentBuilder constructs values. Every setter returns the " +
				"builder, so calls chain. A builder is a value under construction " +
				"and is not safe for concurrent use; [CommentBuilder.Clone] is how " +
				"one becomes two.",
		)
		for line := range strings.SplitSeq(got, "\n") {
			if len(line) > golang.DocWidth+len("// ") {
				t.Errorf("line is %d columns, want at most %d: %q",
					len(line), golang.DocWidth+3, line)
			}
		}
	})

	t.Run("every line carries the comment marker", func(t *testing.T) {
		t.Parallel()
		for line := range strings.SplitSeq(golang.WrapDoc("one two three"), "\n") {
			if !strings.HasPrefix(line, "//") {
				t.Errorf("line %q is not a comment; a template pasting this into "+
					"source would emit it as code", line)
			}
		}
	})

	t.Run("a blank line separates paragraphs", func(t *testing.T) {
		t.Parallel()
		// godoc reads a blank comment line as a paragraph break, so a
		// helper that dropped it would run a summary into its body and
		// leave the symbol with a four-sentence first line.
		got := golang.WrapDoc("First paragraph.\n\nSecond paragraph.")
		if !strings.Contains(got, "\n//\n") {
			t.Errorf("got %q, want the paragraphs separated by a bare marker", got)
		}
	})

	t.Run("an over-long word takes a line of its own", func(t *testing.T) {
		t.Parallel()
		// The words that reach that length here are identifiers and
		// import paths, and a broken one stops being a link godoc
		// resolves.
		long := strings.Repeat("x", golang.DocWidth+10)
		if got := golang.WrapDoc("see " + long); !strings.Contains(got, "// "+long) {
			t.Errorf("got %q, want the long word intact on its own line", got)
		}
	})

	t.Run("empty text renders nothing", func(t *testing.T) {
		t.Parallel()
		if got := golang.WrapDoc("   \n  "); got != "//" {
			t.Errorf("got %q; a symbol with nothing to say still needs a "+
				"well-formed comment rather than a bare prefix with a space", got)
		}
	})
}
