// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.thesmos.sh/eidos/cli"
	"go.thesmos.sh/eidos/core/diag"
	"go.thesmos.sh/eidos/lang/typescript"
	backendts "go.thesmos.sh/eidos/lang/typescript/backend"
	"go.thesmos.sh/eidos/plugin"
	"go.thesmos.sh/eidos/sdk"
)

// TestTypeScriptTargetE2E performs the swap [defaultPlugins]'s doc
// comment prescribes: the same universe with the Go backend replaced
// by the TypeScript one, driven through the binary's own run path
// over real TypeScript source, to a real file on disk.
//
// It earns its place as the wiring claim's proof. A pipeline takes
// exactly one backend, so the default set cannot carry both — which
// means nothing else exercises "a TypeScript-targeting binary is this
// binary with one entry swapped". The in-process round trip in
// typescripttest covers rendering; this covers config discovery, the
// run command, the disk sink and the manifest around it.
func TestTypeScriptTargetE2E(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	src := `export interface User {
  readonly id: string;
  nick?: string;
}
`
	if err := os.WriteFile(filepath.Join(dir, "user.ts"), []byte(src), 0o600); err != nil {
		t.Fatalf("write source: %v", err)
	}
	// The frontend resolves patterns against its dir option rather
	// than the process working directory, and the config file is how a
	// real invocation sets it — which puts discovery of `.<brand>.yaml`
	// under this test too.
	cfg := "plugins:\n  - name: typescript\n    options:\n      dir: " + dir + "\n"
	if err := os.WriteFile(filepath.Join(dir, "."+brand+".yaml"), []byte(cfg), 0o600); err != nil {
		t.Fatalf("write config: %v", err)
	}

	var stdout, stderr bytes.Buffer
	env := &cli.Env{
		Brand:   brand,
		Workdir: dir,
		Stdin:   strings.NewReader(""),
		Stdout:  &stdout,
		Stderr:  &stderr,
		Diag:    diag.New(),
	}

	code := run(t.Context(), env, typescriptTarget(), []string{"run", "./..."})
	if code != cli.ExitOK {
		t.Fatalf("run exited %d\nstdout:\n%s\nstderr:\n%s", code, stdout.String(), stderr.String())
	}

	out := filepath.Join(dir, "user_echo.gen.ts")
	body, err := os.ReadFile(out) //nolint:gosec // a test-owned path
	if err != nil {
		t.Fatalf("no generated file at %s: %v\nstdout:\n%s\nstderr:\n%s",
			out, err, stdout.String(), stderr.String())
	}
	for _, want := range []string{
		"// Code generated by eidos. DO NOT EDIT.",
		"export interface UserEcho {",
		"readonly id: string;",
		"nick?: string;",
	} {
		if !strings.Contains(string(body), want) {
			t.Errorf("output missing %q:\n%s", want, body)
		}
	}
}

// typescriptTarget returns the binary's universe with the backend
// swapped and one TypeScript generator added — the reference set's
// generators are Go-flavoured, and a run that generates nothing would
// prove the pipeline builds without proving it writes.
func typescriptTarget() []plugin.Plugin {
	plugins := defaultPlugins()
	for i, p := range plugins {
		if _, ok := p.(plugin.Backend); ok {
			plugins[i] = backendts.New()
		}
	}
	return append(plugins, newTSEcho())
}

// tsEcho mirrors every source interface into an emit interface,
// carrying the two member stamps the assertion reads back.
type tsEcho struct{ *sdk.Base }

func newTSEcho() *tsEcho {
	return &tsEcho{Base: sdk.NewPlugin("ts-echo").
		Version("1.0.0").
		For(backendts.Language, sdk.LanguageSupport{
			Outputs: []sdk.Output{{Suffix: "_echo.gen.ts"}},
			Builtin: true,
		}).
		Build()}
}

// Generate implements [plugin.Generator].
func (*tsEcho) Generate(ctx *sdk.GeneratorContext) error {
	c := sdk.NewProvenance("ts-echo")
	for _, pkg := range ctx.Reader.Packages().Slice() {
		if len(pkg.Interfaces) == 0 {
			continue
		}
		b := c.Package(pkg.Name, pkg.Path)
		for _, src := range pkg.Interfaces {
			b.Interface(src.Name+"Echo", func(ib *sdk.InterfaceBuilder) {
				ib.Origin(src)
				for _, f := range src.Fields {
					ib.Field(f.Name, sdk.Builtin("string"), func(fb *sdk.FieldBuilder) {
						copyStamp(f, fb.Node())
					})
				}
			})
		}
		built, err := b.Build()
		if err != nil {
			return err
		}
		if err := ctx.Store.Emit().AddPackage(built); err != nil {
			return err
		}
	}
	return nil
}

// copyStamp carries the readonly and optional markers across, which
// is what lets the assertion prove the frontend's stamps reached the
// rendered file through the binary's own path.
func copyStamp(src, dst interface{ EnsureMeta() *sdk.Bag }) {
	for _, key := range []sdk.Key[bool]{
		typescript.MetaReadonly, typescript.MetaOptional,
	} {
		if v, ok := key.Get(src.EnsureMeta()); ok {
			key.Set(dst.EnsureMeta(), v, "ts-echo")
		}
	}
}
