// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package frontend_test

import (
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"go.thesmos.sh/eidos/cache"
	"go.thesmos.sh/eidos/core/diag"
	"go.thesmos.sh/eidos/core/directive"
	"go.thesmos.sh/eidos/core/opt"
	"go.thesmos.sh/eidos/lang/golang/frontend"
	"go.thesmos.sh/eidos/node"
	"go.thesmos.sh/eidos/plugin"
	"go.thesmos.sh/eidos/store"
)

// chdirMu serialises [os.Chdir] across every concurrent test that
// points the Go frontend at a fixture directory. The working
// directory is process-global, so two parallel goroutines both
// chdir'ing into their own temp dirs would race — one would
// observe the other's dir when calling [packages.Load]. The lock
// is held only for the chdir + load window, which is short
// (single-package loads finish in tens of milliseconds), so
// parallel test suites still scale.
var chdirMu sync.Mutex //nolint:gochecknoglobals // process-wide chdir serialiser

// defaultGoMod is the synthesised go.mod content used when a
// fixture's source map does not supply one. The module path is
// arbitrary but stable so cache keys produced inside a single test
// remain comparable.
const defaultGoMod = "module example.com/golangtest\n\ngo 1.26\n"

// loadFromSource materialises src into a fresh temp module and
// drives the Go frontend directly into a fresh [*store.Store]. The
// returned diag sink carries every diagnostic the frontend produced;
// callers inspect the store for converted nodes and the sink for
// errors / warnings.
func loadFromSource(t *testing.T, src map[string]string) (*store.Store, *diag.Sink) {
	t.Helper()
	dir := materialiseGoSource(t, src)
	return loadDir(t, dir, nil)
}

// firstPackageIn returns the first [node.Package] whose path
// contains pathSubstr, or nil when no match exists. Tests use a
// path substring rather than a full match because the temp-module
// path generated by [materialiseGoSource] varies across runs.
func firstPackageIn(s *store.Store, pathSubstr string) *node.Package {
	var out *node.Package
	s.Nodes().Packages().Range(func(pkg *node.Package) bool {
		if pathSubstr == "" || strings.Contains(pkg.Path, pathSubstr) {
			out = pkg
			return false
		}
		return true
	})
	return out
}

// requirePackage loads src, asserts no errors, and returns the
// first non-builtin package in the store. Used by per-decl tests
// that don't care about pipeline plumbing.
func requirePackage(t *testing.T, src map[string]string) *node.Package {
	t.Helper()
	s, d := loadFromSource(t, src)
	if d.HasErrors() {
		t.Fatalf("unexpected frontend errors: %+v", d.Diagnostics())
	}
	pkg := firstPackageIn(s, "")
	if pkg == nil {
		t.Fatalf("no package loaded from source map %v", src)
	}
	return pkg
}

// requirePackageOpts is [requirePackage] with frontend options.
// Used by tests that need to flip option defaults (skipping
// generated files, including tests, …) before observing the loaded
// package.
func requirePackageOpts(t *testing.T, src, opts map[string]string) *node.Package {
	t.Helper()
	dir := materialiseGoSource(t, src)
	s, d := loadDirWithOptions(t, dir, nil, opts)
	if d.HasErrors() {
		t.Fatalf("unexpected frontend errors: %+v", d.Diagnostics())
	}
	pkg := firstPackageIn(s, "")
	if pkg == nil {
		t.Fatalf("no package loaded from source map %v", src)
	}
	return pkg
}

// materialiseGoSource writes the supplied source map into a fresh
// [testing.T.TempDir] and returns the directory path. A `go.mod`
// is synthesised when the map does not supply one so the directory
// loads as a self-contained module.
func materialiseGoSource(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	hasGoMod := false
	for path, body := range files {
		if path == "go.mod" {
			hasGoMod = true
		}
		writeMaterialisedFile(t, dir, path, body)
	}
	if !hasGoMod {
		writeMaterialisedFile(t, dir, "go.mod", defaultGoMod)
	}
	return dir
}

// writeMaterialisedFile writes one entry from the source map to the
// temp directory, creating any intermediate directories.
func writeMaterialisedFile(t *testing.T, dir, rel, content string) {
	t.Helper()
	full := filepath.Join(dir, rel)
	parent := filepath.Dir(full)
	if err := os.MkdirAll(parent, 0o750); err != nil {
		t.Fatalf("mkdir %s: %v", parent, err)
	}
	if err := os.WriteFile(full, []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", full, err)
	}
}

// loadDir drives a fresh frontend over dir using cache c, returning
// the populated store and diag sink. Serialises chdir across
// concurrent callers in the same test binary so two parallel
// loaders do not race on the process-global working directory.
//
// Uses raw [os.Chdir] rather than [testing.T.Chdir] because the
// caller is typically a t.Parallel() subtest, and t.Chdir refuses
// to run in parallel contexts even when the chdir is correctly
// serialised by the package-level mutex.
func loadDir(t *testing.T, dir string, c cache.Cache) (*store.Store, *diag.Sink) {
	t.Helper()
	return loadDirWithOptions(t, dir, c, nil)
}

// loadDirWithOptions is the [loadDir] variant that configures
// frontend [frontend.Options] before invoking [Frontend.Load]. The
// values map keys are the option JSON tags ("include_tests",
// "build_tags", "skip_cgo_files"); a nil or empty map produces the
// default options.
func loadDirWithOptions(t *testing.T, dir string, c cache.Cache, values map[string]string) (*store.Store, *diag.Sink) {
	t.Helper()
	chdirMu.Lock()
	defer chdirMu.Unlock()
	prev, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil { //nolint:usetesting // t.Chdir() rejects parallel tests
		t.Fatalf("chdir: %v", err)
	}
	defer func() { _ = os.Chdir(prev) }() //nolint:usetesting // t.Chdir() rejects parallel tests

	s := store.New()
	d := diag.New()
	fe := frontend.New()
	if len(values) > 0 {
		if err := fe.SetOptions(opt.New(fe.OptionsSchema(), values)); err != nil {
			t.Fatalf("SetOptions: %v", err)
		}
	}
	if err := fe.Load(&plugin.FrontendContext{
		Store:   s,
		Diag:    d,
		Parser:  directive.DefaultParser(),
		Cache:   c,
		Pattern: "./...",
	}); err != nil {
		t.Fatalf("Load: %v", err)
	}
	return s, d
}

// assertNoPanicDiagnostic fails when any diagnostic in d carries the
// recovered-panic marker the pipeline's plugin guard stamps.
//
// The pipeline recovers a panicking plugin into a diagnostic, so a
// test that merely reached its end proves nothing — the panic was
// swallowed on the way. Asserting on the diagnostics is the only way
// to tell "reported the problem" from "fell over while reporting
// it".
func assertNoPanicDiagnostic(t *testing.T, d *diag.Sink) {
	t.Helper()
	for _, got := range d.Diagnostics() {
		if strings.Contains(got.Message, "panicked") {
			t.Fatalf("frontend panicked instead of reporting: %s", got.Message)
		}
	}
}

// assertRedeclarationReported drives the frontend over src — which
// must contain a duplicate declaration — and asserts the frontend
// reports it rather than panicking.
//
// go/types records a nil Defs entry for the *losing* side of a
// redeclaration, and go/types keeps the declaration it sees first.
// Callers therefore put the kind under test in the later-sorting
// file, or the case silently exercises the winning side and proves
// nothing.
func assertRedeclarationReported(t *testing.T, src map[string]string) {
	t.Helper()
	_, d := loadFromSource(t, src)
	if !d.HasErrors() {
		t.Fatalf("a redeclaration must be reported; got no errors")
	}
	assertNoPanicDiagnostic(t, d)
}
