// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golangtest_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.thesmos.sh/eidos/eidostest/golangtest"
)

// surfaced is a generated file carrying one of everything the API
// rendering has an arm for.
const surfaced = `// Code generated by eidos. DO NOT EDIT.

package storepkg

import "io"

type Box[T any] struct {
	io.Closer

	Value  T
	hidden string
}

type Reader interface {
	io.Closer
	Read(p []byte) (int, error)
	unexported()
}

type alias = string

var Sentinel error

var unexported int

func (b *Box[T]) Get() T { var z T; return z }

func (b Box[T]) Len() int { return 0 }

func (b *Box[T]) hidden() {}

func New() *Box[string] { return nil }

func helper() {}
`

// api renders the surfaced fixture's exported API.
func api(t *testing.T) string {
	t.Helper()
	return golangtest.Parse(t, golangtest.File{Path: "box.gen.go", Src: []byte(surfaced)}).API()
}

func TestAPISurface(t *testing.T) {
	t.Parallel()

	t.Run("carries the package clause", func(t *testing.T) {
		t.Parallel()
		if !strings.HasPrefix(api(t), "package storepkg\n") {
			t.Fatalf("API = %q", api(t))
		}
	})

	t.Run("renders an exported func and its receiver form", func(t *testing.T) {
		t.Parallel()
		// A value receiver puts the method on both forms and a pointer
		// receiver on one, so the form is surface.
		got := api(t)
		for _, want := range []string{
			"func (*Box) Get() T",
			"func (Box) Len() int",
			"func New() *Box[string]",
		} {
			if !strings.Contains(got, want) {
				t.Fatalf("API does not carry %q\n%s", want, got)
			}
		}
	})

	t.Run("expands a struct to its exported fields and embeds", func(t *testing.T) {
		t.Parallel()
		if !strings.Contains(api(t), "type Box[T any] struct{Value T; io.Closer}") {
			t.Fatalf("API = %s", api(t))
		}
	})

	t.Run("expands an interface to its exported method set", func(t *testing.T) {
		t.Parallel()
		const want = "type Reader interface{Read(p []byte) (int, error); io.Closer}"
		if !strings.Contains(api(t), want) {
			t.Fatalf("API = %s", api(t))
		}
	})

	t.Run("carries an exported var and its type", func(t *testing.T) {
		t.Parallel()
		if !strings.Contains(api(t), "var Sentinel error") {
			t.Fatalf("API = %s", api(t))
		}
	})

	t.Run("drops everything a consumer cannot observe", func(t *testing.T) {
		t.Parallel()
		// The whole point: a golden over this changes only when a
		// consumer's code would have to.
		got := api(t)
		for _, absent := range []string{"hidden", "unexported", "helper", "Code generated"} {
			if strings.Contains(got, absent) {
				t.Fatalf("API carries %q, which no consumer can observe\n%s", absent, got)
			}
		}
	})

	t.Run("is stable under reordering and reformatting", func(t *testing.T) {
		t.Parallel()
		// A generator that reorders struct fields or reflows a comment
		// offers a consumer nothing new, and must produce no diff.
		reordered := strings.Replace(surfaced,
			"\tValue  T\n\thidden string\n", "\thidden string\n\tValue T\n", 1)
		reordered = strings.Replace(reordered,
			"// Code generated by eidos. DO NOT EDIT.",
			"// Code generated by eidos. DO NOT EDIT.\n//\n// A new comment nobody depends on.", 1)
		other := golangtest.Parse(t, golangtest.File{Path: "b.go", Src: []byte(reordered)}).API()
		if other != api(t) {
			t.Fatalf("API moved on a change no consumer can see\n--- got ---\n%s\n--- want ---\n%s",
				other, api(t))
		}
	})

	t.Run("moves when a signature changes", func(t *testing.T) {
		t.Parallel()
		changed := strings.Replace(surfaced, "func New() *Box[string]", "func New() *Box[int]", 1)
		other := golangtest.Parse(t, golangtest.File{Path: "b.go", Src: []byte(changed)}).API()
		if other == api(t) {
			t.Fatal("API did not move on a change every consumer has to react to")
		}
	})
}

func TestAPIGolden(t *testing.T) {
	t.Parallel()

	t.Run("writes a golden that does not exist yet", func(t *testing.T) {
		t.Parallel()
		// The first run after adding a fixture records the surface rather
		// than demanding the author type it out.
		path := filepath.Join(t.TempDir(), "nested", "box.api")
		src := golangtest.Parse(t, golangtest.File{Path: "box.gen.go", Src: []byte(surfaced)})
		golangtest.AssertAPIGolden(t, src, path)

		written, err := os.ReadFile(path) //nolint:gosec // a path this test just composed.
		if err != nil {
			t.Fatalf("the golden was not written: %v", err)
		}
		if string(written) != src.API() {
			t.Fatalf("the golden does not hold the surface")
		}
	})

	t.Run("accepts a golden that matches", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "box.api")
		src := golangtest.Parse(t, golangtest.File{Path: "box.gen.go", Src: []byte(surfaced)})
		golangtest.AssertAPIGolden(t, src, path)
		golangtest.AssertAPIGolden(t, src, path)
	})

	t.Run("reports a surface that moved", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "box.api")
		if err := os.WriteFile(path, []byte("package storepkg\n\nfunc Old()\n"), 0o600); err != nil {
			t.Fatalf("seed the golden: %v", err)
		}
		s := probe(t)
		golangtest.AssertAPIGolden(s, golangtest.Parse(t, golangtest.File{
			Path: "box.gen.go", Src: []byte(surfaced),
		}), path)
		if !s.failed || !strings.Contains(s.msg, "consumer would have to react to") {
			t.Fatalf("AssertAPIGolden = %v, %q", s.failed, s.msg)
		}
	})
}
