// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golangtest_test

import (
	"strings"
	"testing"

	"go.thesmos.sh/eidos/eidostest/golangtest"
	"go.thesmos.sh/eidos/eidostest/pipelinetest"
	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/node"
	"go.thesmos.sh/eidos/plugin"
)

// writingBackend renders a fixed set of targets, standing in for a
// real backend so the adoption path is exercised end to end rather
// than assumed.
type writingBackend struct{ writes map[emit.Target][]byte }

func (*writingBackend) Name() string     { return "golangtest-fixture" }
func (*writingBackend) Language() string { return golangtest.Language }

func (b *writingBackend) Render(ctx *plugin.BackendContext) error {
	for tgt, body := range b.writes {
		if err := ctx.Sink.Write(tgt, body); err != nil {
			return err
		}
	}
	return nil
}

// routed drives a pipeline that writes a primary and a companion, the
// second into a subpackage — the arrangement every real generator
// produces and the one a flattened module would resolve by accident.
func routed(t *testing.T) *pipelinetest.Pipeline {
	t.Helper()
	return pipelinetest.New(t).
		WithFrontend(pipelinetest.FromNodes(&node.Package{
			Name: "storepkg", Path: "example.com/storepkg",
		})).
		WithBackend(&writingBackend{writes: map[emit.Target][]byte{
			{Filename: "printer_stub.gen.go", ImportPath: "example.com/storepkg"}: []byte(goodDouble),
			{
				Dir:        "storetest",
				Filename:   "printer_stub.gen_test.go",
				ImportPath: "example.com/storepkg/storetest",
			}: []byte("// Code generated by eidos. DO NOT EDIT.\n\npackage storetest_test\n"),
		}}).
		Build().
		Run()
}

func TestRendered(t *testing.T) {
	t.Parallel()

	t.Run("adopts every file the run wrote", func(t *testing.T) {
		t.Parallel()
		got := golangtest.Rendered(t, routed(t)).Files()
		if len(got) != 2 {
			t.Fatalf("Rendered captured %d file(s): %v", len(got), got)
		}
	})

	t.Run("keeps the directory a routed file landed in", func(t *testing.T) {
		t.Parallel()
		// Two files in one directory are one package; flattening them
		// would make a cross-package reference resolve for the wrong
		// reason and hide the bug it was meant to catch.
		g := golangtest.Rendered(t, routed(t))
		if got := g.Suffixed(t, ".gen_test.go").Path(); got != "storetest/printer_stub.gen_test.go" {
			t.Fatalf("path = %q, want the routed directory", got)
		}
	})

	t.Run("orders the files so a failure reads the same twice", func(t *testing.T) {
		t.Parallel()
		// The sink hands them back from a map, and every failure message
		// lists what it looked at.
		first := golangtest.Rendered(t, routed(t)).Files()
		second := golangtest.Rendered(t, routed(t)).Files()
		for i := range first {
			if first[i].Path != second[i].Path {
				t.Fatalf("file order is unstable: %v then %v", first, second)
			}
		}
	})

	t.Run("derives the module path by stripping the routed directory", func(t *testing.T) {
		t.Parallel()
		// `example.com/storepkg/storetest` in `storetest/` belongs to the
		// module `example.com/storepkg`, and declaring that is what makes
		// the generated import resolve.
		golangtest.Rendered(t, routed(t)).
			WithSource(golangtest.File{Path: "printer.go", Src: []byte(sourcePkg)}).
			AssertCompiles(t)
	})

	t.Run("finds the primary among a routed set", func(t *testing.T) {
		t.Parallel()
		golangtest.Rendered(t, routed(t)).Primary(t).AssertPackage(t, "storepkg")
	})
}

func TestModuleOptions(t *testing.T) {
	t.Parallel()

	t.Run("honours an explicit module path", func(t *testing.T) {
		t.Parallel()
		golangtest.Of(golangtest.File{
			Path: "a.go", Src: []byte("package a\n\nfunc F() {}\n"),
		}).WithModulePath("example.com/pinned").AssertCompiles(t)
	})

	t.Run("honours a pinned Go version", func(t *testing.T) {
		t.Parallel()
		// A template that starts emitting a later release's syntax raises
		// every consumer's floor, and nothing else would notice.
		golangtest.Of(golangtest.File{
			Path: "a.go", Src: []byte("package a\n\nfunc F() {}\n"),
		}).WithGoVersion("1.24").AssertCompiles(t)
	})

	t.Run("reports output using syntax the pinned version lacks", func(t *testing.T) {
		t.Parallel()
		// `for range n` over an integer is Go 1.22; pinned below it, the
		// same output stops building.
		s := probe(t)
		golangtest.Of(golangtest.File{
			Path: "a.go",
			Src:  []byte("package a\n\nfunc F() {\n\tfor range 3 {\n\t}\n}\n"),
		}).WithGoVersion("1.21").AssertCompiles(s)
		if !s.failed {
			t.Fatal("a pinned Go version did not constrain the build")
		}
	})
}

func TestAddressing(t *testing.T) {
	t.Parallel()

	g := gen(t, goodDouble, golangtest.File{
		Path:       "printer_stub.gen_test.go",
		Src:        []byte(generatedSuite),
		ImportPath: "example.com/storepkg",
	})

	t.Run("finds the primary without knowing the composed filename", func(t *testing.T) {
		t.Parallel()
		g.Primary(t).AssertPackage(t, "storepkg")
	})

	t.Run("finds a file by the suffix its plugin declared", func(t *testing.T) {
		t.Parallel()
		// The vocabulary a plugin author already has: they declared the
		// suffix, and Layout composed the rest from a source basename.
		g.Suffixed(t, ".gen_test.go").AssertPackage(t, "storepkg_test")
	})

	t.Run("finds a file by path", func(t *testing.T) {
		t.Parallel()
		g.File(t, "printer_stub.gen.go").AssertPackage(t, "storepkg")
	})

	t.Run("lists every file in a stable order", func(t *testing.T) {
		t.Parallel()
		// Map iteration is unordered, and every failure message lists the
		// files it looked at.
		files := g.Files()
		if len(files) != 2 || files[0].Path != "printer_stub.gen.go" {
			t.Fatalf("Files = %v", files)
		}
	})

	t.Run("reports a directory on a routed file", func(t *testing.T) {
		t.Parallel()
		f := golangtest.File{Path: "storetest/x.gen.go"}
		if f.Dir() != "storetest" || f.IsTest() {
			t.Fatalf("Dir = %q, IsTest = %v", f.Dir(), f.IsTest())
		}
	})
}

func TestInModule(t *testing.T) {
	t.Parallel()

	t.Run("builds inside a copy of an existing module", func(t *testing.T) {
		t.Parallel()
		// The escape hatch for output referencing packages a bare temp
		// module could not resolve: the fixture's go.mod and its files
		// come along, and the generated file is written over the top.
		const src = "package consumer\n\n" +
			"// Doubled uses the module's own symbol.\n" +
			"func Doubled() int { return Helper() * 2 }\n"
		golangtest.Of(golangtest.File{Path: "generated.gen.go", Src: []byte(src)}).
			InModule("testdata/consumer").
			AssertCompiles(t)
	})

	t.Run("still reports output the copied module cannot build", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		golangtest.Of(golangtest.File{
			Path: "generated.gen.go",
			Src:  []byte("package consumer\n\nfunc Broken() int { return Absent() }\n"),
		}).InModule("testdata/consumer").AssertCompiles(s)
		if !s.failed {
			t.Fatal("InModule accepted output the module cannot build")
		}
	})
}

func TestAddressingFailures(t *testing.T) {
	t.Parallel()

	two := golangtest.Of(
		golangtest.File{Path: "a.gen.go", Src: []byte("package a\n")},
		golangtest.File{Path: "b.gen.go", Src: []byte("package a\n")},
	)

	t.Run("names every file when one is absent", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		two.File(s, "absent.go")
		if !s.failed || !strings.Contains(s.msg, "a.gen.go") {
			t.Fatalf("message %q does not list the files", s.msg)
		}
	})

	t.Run("refuses a suffix matching nothing", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		two.Suffixed(s, "_test.go")
		if !s.failed || !strings.Contains(s.msg, "no file ending in") {
			t.Fatalf("message %q", s.msg)
		}
	})

	t.Run("refuses a suffix matching several", func(t *testing.T) {
		t.Parallel()
		// Guessing which one the caller meant would make the assertion
		// depend on sort order rather than on intent.
		s := probe(t)
		two.Suffixed(s, ".gen.go")
		if !s.failed || !strings.Contains(s.msg, "2 files end in") {
			t.Fatalf("message %q", s.msg)
		}
	})

	t.Run("refuses to guess the primary among several", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		two.Primary(s)
		if !s.failed || !strings.Contains(s.msg, "2 non-test files") {
			t.Fatalf("message %q", s.msg)
		}
	})

	t.Run("reports a run that produced no primary at all", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		golangtest.Of(golangtest.File{Path: "a_test.go", Src: []byte("package a\n")}).Primary(s)
		if !s.failed || !strings.Contains(s.msg, "no non-test file") {
			t.Fatalf("message %q", s.msg)
		}
	})
}

func TestModulePathDerivation(t *testing.T) {
	t.Parallel()

	t.Run("strips a routed directory from the import path", func(t *testing.T) {
		t.Parallel()
		// A file in `storetest/` with import path
		// `example.com/storepkg/storetest` belongs to the module
		// `example.com/storepkg`.
		golangtest.Of(golangtest.File{
			Path:       "storetest/a.gen.go",
			Src:        []byte("package storetest\n"),
			ImportPath: "example.com/storepkg/storetest",
		}).AssertCompiles(t)
	})

	t.Run("falls back when the run resolved no import path", func(t *testing.T) {
		t.Parallel()
		// The default names no registrable domain, so output reaching the
		// network for it fails loudly rather than resolving something.
		golangtest.Of(golangtest.File{Path: "a.gen.go", Src: []byte("package a\n")}).
			AssertCompiles(t)
	})
}

func TestGoVersionFrom(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name string
		raw  string
		want string
	}{
		{"drops the patch from a release toolchain", "go1.26.5", "1.26"},
		{"accepts a two-part version", "go1.24", "1.24"},
		{"falls back for a devel build", "devel go1.27-abc123", "1.24"},
		{"falls back for a version with no minor", "go1", "1.24"},
		{"falls back for a non-numeric minor", "go1.x", "1.24"},
		{"falls back for an empty string", "", "1.24"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			// A version go.mod would reject makes every toolchain
			// assertion fail for a reason that is about the test host
			// rather than about the generated code.
			if got := golangtest.GoVersionFrom(tc.raw); got != tc.want {
				t.Fatalf("GoVersionFrom(%q) = %q, want %q", tc.raw, got, tc.want)
			}
		})
	}
}
