// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golangtest_test

import (
	"fmt"
	"testing"

	"go.thesmos.sh/eidos/eidostest/golangtest"
)

// primary is a generated file shaped like the ones the corpus
// produces: a generated header, an external dependency, a struct with
// an embed and a field, a constructor and a method.
const primary = `// Code generated by eidos. DO NOT EDIT.

package storepkg

import (
	"context"
	"io"
)

// StoreGetStub records calls to Get.
type StoreGetStub struct {
	io.Closer

	OnGet   *StoreGetStub
	hidden  string
}

// StoreStub stands in for Store.
type StoreStub struct {
	OnGet *StoreGetStub
}

func NewStoreStub(tb TB, opts ...StoreStubOption) *StoreStub {
	return &StoreStub{}
}

func (s *StoreStub) Get(ctx context.Context, id string) (string, error) {
	r := answer(s.OnGet)
	return r.Item, r.Err
}

func (s *StoreStub) Close() {
}

func (s StoreStub) Name() string { return "store" }
`

// generatedTests is a generated companion, the shape whose subtest
// names three plugins assert on as substrings today.
const generatedTests = `// Code generated by eidos. DO NOT EDIT.

package storepkg_test

import "testing"

func TestStoreStubGet(t *testing.T) {
	t.Parallel()

	t.Run("records what it was called with", func(t *testing.T) {
		t.Parallel()
	})
	t.Run("answers with the value pinned by Returns", func(t *testing.T) {
	})
}

func TestStoreStubClose(t *testing.T) {
	t.Run("records what it was called with", func(t *testing.T) {
	})
}
`

// parse reads the primary fixture.
func parse(t *testing.T) *golangtest.Source {
	t.Helper()
	return golangtest.Parse(t, golangtest.File{Path: "store_stub.gen.go", Src: []byte(primary)})
}

// parseTests reads the companion fixture.
func parseTests(t *testing.T) *golangtest.Source {
	t.Helper()
	return golangtest.Parse(t, golangtest.File{
		Path: "store_stub.gen_test.go", Src: []byte(generatedTests),
	})
}

// spy captures what an assertion reported instead of failing the
// test, so a test can assert that a failing assertion fails — and
// that its message diagnoses rather than merely denies, which is
// most of what these assertions are for.
//
// The embedded TB delegates everything else, so a spy is a drop-in
// for the real one at every call site.
type spy struct {
	testing.TB

	failed bool
	msg    string
}

func (s *spy) Errorf(format string, args ...any) {
	s.failed = true
	s.msg = fmt.Sprintf(format, args...)
}

// Fatalf records and returns.
//
// The real one stops the goroutine, which would make every
// stop-the-test branch untestable. Returning is safe only because the
// assertions that use Fatalf return a nil or zero value immediately
// after, and the tests below check that rather than dereferencing it.
func (s *spy) Fatalf(format string, args ...any) {
	s.failed = true
	s.msg = fmt.Sprintf(format, args...)
}

// probe returns a spy over t.
func probe(t *testing.T) *spy {
	t.Helper()
	return &spy{TB: t}
}

// sourcePkg is the hand-written package a generated double
// references — the file a consumer wrote, which nothing generated and
// without which none of the output compiles.
const sourcePkg = `package storepkg

// Printer is the interface the double stands in for. Print is
// variadic, which is the marker a projection most easily drops.
type Printer interface {
	Print(args ...string)
	Close() error
}
`

// goodDouble satisfies Printer.
const goodDouble = `// Code generated by eidos. DO NOT EDIT.

package storepkg

type PrinterStub struct{}

func (s *PrinterStub) Print(args ...string) {}

func (s *PrinterStub) Close() error { return nil }
`

// variadicDropped is the same double with the variadic marker lost —
// the bug live in two reference generators today. It compiles, it
// type-checks, and it satisfies nothing.
const variadicDropped = `// Code generated by eidos. DO NOT EDIT.

package storepkg

type PrinterStub struct{}

func (s *PrinterStub) Print(args string) {}

func (s *PrinterStub) Close() error { return nil }
`

// generatedSuite is a companion that passes.
const generatedSuite = `// Code generated by eidos. DO NOT EDIT.

package storepkg_test

import (
	"testing"

	"example.com/storepkg"
)

func TestPrinterStubPrint(t *testing.T) {
	t.Parallel()

	s := &storepkg.PrinterStub{}
	s.Print("a")
	if err := s.Close(); err != nil {
		t.Fatalf("Close = %v", err)
	}
}
`

// gen assembles a Generated over the double and its source package.
func gen(t *testing.T, double string, extra ...golangtest.File) *golangtest.Generated {
	t.Helper()
	files := append([]golangtest.File{{
		Path:       "printer_stub.gen.go",
		Src:        []byte(double),
		ImportPath: "example.com/storepkg",
	}}, extra...)
	return golangtest.Of(files...).
		WithSource(golangtest.File{Path: "printer.go", Src: []byte(sourcePkg)})
}
