// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golangtest_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.thesmos.sh/eidos/eidostest/golangtest"
)

func TestParse(t *testing.T) {
	t.Parallel()

	t.Run("reads a well-formed file", func(t *testing.T) {
		t.Parallel()
		if got := parse(t).Path(); got != "store_stub.gen.go" {
			t.Fatalf("Path = %q", got)
		}
	})

	t.Run("keeps the bytes it was given", func(t *testing.T) {
		t.Parallel()
		if string(parse(t).Bytes()) != primary {
			t.Fatalf("Bytes did not round-trip")
		}
	})
}

func TestPackageAndImports(t *testing.T) {
	t.Parallel()

	t.Run("reports the declared package", func(t *testing.T) {
		t.Parallel()
		parse(t).AssertPackage(t, "storepkg")
	})

	t.Run("lists every import", func(t *testing.T) {
		t.Parallel()
		parse(t).AssertImports(t, "context", "io").AssertNoImport(t, "reflect")
	})

	t.Run("pins the whole import set", func(t *testing.T) {
		t.Parallel()
		// A generator's imports are API: one added silently breaks every
		// consumer whose module does not already require it.
		parse(t).AssertImportsOnly(t, "io", "context")
	})

	t.Run("names what is unexpected and what is absent", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		parse(t).AssertImportsOnly(s, "context", "reflect")
		if !s.failed {
			t.Fatal("AssertImportsOnly accepted the wrong set")
		}
		for _, want := range []string{"unexpected: [io]", "absent: [reflect]"} {
			if !strings.Contains(s.msg, want) {
				t.Fatalf("message %q does not carry %q", s.msg, want)
			}
		}
	})
}

func TestGeneratedHeader(t *testing.T) {
	t.Parallel()

	t.Run("accepts the conventional line", func(t *testing.T) {
		t.Parallel()
		parse(t).AssertGeneratedHeader(t)
	})

	t.Run("rejects a header that drifted", func(t *testing.T) {
		t.Parallel()
		// Tooling keys off the exact spelling, so a near-miss opts every
		// consumer's output back into linting and review.
		drifted := strings.Replace(primary, "DO NOT EDIT.", "do not edit.", 1)
		s := probe(t)
		golangtest.Parse(t, golangtest.File{Path: "x.go", Src: []byte(drifted)}).
			AssertGeneratedHeader(s)
		if !s.failed {
			t.Fatal("AssertGeneratedHeader accepted a drifted header")
		}
	})
}

func TestFormatted(t *testing.T) {
	t.Parallel()

	t.Run("rejects output the backend did not format", func(t *testing.T) {
		t.Parallel()
		// The fixture's struct is deliberately misaligned, which is what
		// an unformatted generated file looks like in a consumer's next
		// `gofmt -l` run.
		s := probe(t)
		parse(t).AssertFormatted(s)
		if !s.failed {
			t.Fatal("AssertFormatted accepted misaligned source")
		}
	})

	t.Run("accepts canonical output", func(t *testing.T) {
		t.Parallel()
		golangtest.Parse(t, golangtest.File{
			Path: "x.go", Src: []byte("package x\n\nfunc F() {}\n"),
		}).AssertFormatted(t)
	})
}

func TestOrder(t *testing.T) {
	t.Parallel()

	t.Run("accepts a declaration that comes first", func(t *testing.T) {
		t.Parallel()
		parse(t).AssertOrder(t, "StoreGetStub", "StoreStub")
	})

	t.Run("rejects one that comes second", func(t *testing.T) {
		t.Parallel()
		// A contribution rendered ahead of the type it hangs off still
		// compiles; only a reader notices.
		s := probe(t)
		parse(t).AssertOrder(s, "StoreStub", "StoreGetStub")
		if !s.failed || !strings.Contains(s.msg, "after") {
			t.Fatalf("AssertOrder = %v, %q", s.failed, s.msg)
		}
	})

	t.Run("names what the file does declare", func(t *testing.T) {
		t.Parallel()
		s := probe(t)
		parse(t).AssertOrder(s, "Absent", "StoreStub")
		if !s.failed || !strings.Contains(s.msg, "StoreGetStub") {
			t.Fatalf("message %q does not list the declarations", s.msg)
		}
	})
}

func TestDump(t *testing.T) {
	t.Parallel()

	t.Run("logs a file with line numbers", func(t *testing.T) {
		t.Parallel()
		parse(t).Dump(t)
	})
}

func TestGolden(t *testing.T) {
	t.Parallel()

	// withCommand is the header the backend stamps the invocation into,
	// which under `go test` is a temp binary path differing every run.
	withCommand := func(cmd string) *golangtest.Source {
		t.Helper()
		src := "// Code generated by eidos. DO NOT EDIT.\n//\n// Command:   " + cmd +
			"\n\npackage storepkg\n"
		return golangtest.Parse(t, golangtest.File{Path: "x.gen.go", Src: []byte(src)})
	}

	t.Run("normalises the volatile header line", func(t *testing.T) {
		t.Parallel()
		// Every generator keeping a golden had already written this
		// privately, and identically.
		got := string(withCommand("/tmp/go-build123/b001/x.test -test.v").Normalised())
		if !strings.Contains(got, golangtest.CommandPlaceholder) {
			t.Fatalf("Normalised did not rewrite the command line:\n%s", got)
		}
		if strings.Contains(got, "go-build123") {
			t.Fatalf("Normalised kept the volatile path:\n%s", got)
		}
	})

	t.Run("leaves a file with no command line alone", func(t *testing.T) {
		t.Parallel()
		if string(parse(t).Normalised()) != primary {
			t.Fatal("Normalised changed a file carrying no command line")
		}
	})

	t.Run("writes a golden that does not exist yet", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "nested", "x.golden")
		withCommand("a").AssertGolden(t, path)
		written, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("the golden was not written: %v", err)
		}
		if !strings.Contains(string(written), golangtest.CommandPlaceholder) {
			t.Fatal("the golden holds the volatile line")
		}
	})

	t.Run("accepts two runs whose invocations differed", func(t *testing.T) {
		t.Parallel()
		// The whole point: the golden is about the generated code rather
		// than about how the suite was invoked.
		path := filepath.Join(t.TempDir(), "x.golden")
		withCommand("/tmp/first.test").AssertGolden(t, path)
		withCommand("/tmp/second.test -run X").AssertGolden(t, path)
	})

	t.Run("reports a file that moved", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "x.golden")
		withCommand("a").AssertGolden(t, path)
		s := probe(t)
		golangtest.Parse(t, golangtest.File{
			Path: "x.gen.go", Src: []byte("package other\n"),
		}).AssertGolden(s, path)
		if !s.failed {
			t.Fatal("AssertGolden accepted a file that moved")
		}
	})
}

func TestDocumented(t *testing.T) {
	t.Parallel()

	t.Run("accepts fully documented output", func(t *testing.T) {
		t.Parallel()
		golangtest.Parse(t, golangtest.File{
			Path: "x.go", Src: []byte(
				"package x\n\n// T is documented.\ntype T struct{}\n\n" +
					"// F is documented.\nfunc F() {}\n\n" +
					"// M is documented.\nfunc (t T) M() {}\n\n" +
					"// Sentinels.\nvar (\n\tErrA error\n\tErrB error\n)\n" +
					"func unexported() {}\n",
			),
		}).AssertDocumented(t)
	})

	t.Run("names every exported declaration carrying no comment", func(t *testing.T) {
		t.Parallel()
		// A consumer whose linter requires comments on exported
		// declarations gets those failures from generated code, and
		// blames themselves.
		s := probe(t)
		golangtest.Parse(t, golangtest.File{
			Path: "x.go", Src: []byte(
				"package x\n\ntype T struct{}\n\nfunc F() {}\n\nfunc (t T) M() {}\n\nvar Err error\n",
			),
		}).AssertDocumented(s)
		if !s.failed {
			t.Fatal("AssertDocumented accepted undocumented API")
		}
		for _, want := range []string{"Err", "F", "T", "T.M"} {
			if !strings.Contains(s.msg, want) {
				t.Fatalf("message %q does not name %q", s.msg, want)
			}
		}
	})

	t.Run("ignores what a consumer cannot name", func(t *testing.T) {
		t.Parallel()
		golangtest.Parse(t, golangtest.File{
			Path: "x.go", Src: []byte(
				"package x\n\ntype hidden struct{}\n\nfunc (h hidden) M() {}\n\nvar unexported int\n",
			),
		}).AssertDocumented(t)
	})
}
