// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golang

import (
	"go/format"
	"go/parser"
	"go/token"
	"strconv"

	"golang.org/x/tools/imports"

	"go.thesmos.sh/eidos/core/diag"
	"go.thesmos.sh/eidos/core/position"
	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/writer"
)

// finaliseBody runs body through the canonical Go finalisation
// chain: [go/format.Source] for gofmt-clean formatting, then the
// goimports library pass for stdlib/external regrouping and import
// hygiene. Neither aborts the surrounding render loop; both fall
// back to the best-available bytes so the user can read what was
// produced.
//
// They differ in severity, and deliberately. A goimports failure is
// a Warn: the body is still valid Go, just not import-tidied. A
// [go/format.Source] failure is an Error, because it means the
// generated bytes do not parse — and a file the formatter cannot
// parse is never a file the compiler can. Reporting that as a
// warning let a run write unparseable Go and exit successfully, so
// the defect surfaced later at `go build`, inside generated code,
// with nothing pointing back at the generator that wrote it.
//
// tracked is the set of import paths the backend recorded during
// template rendering. After goimports completes, any import in the
// finalised output that does not appear in tracked surfaces as one
// Warn per uncovered path — flagging a converter or template bug
// that left an unrecorded type reference behind.
func finaliseBody(body []byte, target emit.Target, ps *diag.PluginSink, tracked []writer.Import) []byte {
	formatted, ok := runGoFormat(body, target, ps)
	if !ok {
		return body
	}
	return runGoImports(formatted, target, ps, trackedPaths(tracked))
}

// runGoFormat runs body through [go/format.Source]. Returns the
// formatted bytes and ok=true on success; on failure attaches an
// Error diagnostic and returns (body, false) so the caller falls
// back to the unformatted bytes.
//
// Error rather than Warn: the formatter refusing the body means the
// body is not syntactically valid Go, so the file cannot compile
// however it is written out. The bytes are still emitted — reading
// the broken output is how a template bug gets diagnosed — but the
// run fails, which is what stops unparseable generated code from
// reaching a build that has no idea where it came from.
func runGoFormat(body []byte, target emit.Target, ps *diag.PluginSink) ([]byte, bool) {
	out, err := format.Source(body)
	if err != nil {
		ps.Errorf(position.Pos{}, "%s: format.Source failed, generated output is not valid Go: %v",
			target.JoinPath(), err)
		return body, false
	}
	return out, true
}

// runGoImports runs the goimports library pass over body. On
// success, untracked imports that goimports added produce one Warn
// per path. On failure, attaches a Warn and falls back to body.
func runGoImports(body []byte, target emit.Target, ps *diag.PluginSink, tracked map[string]struct{}) []byte {
	out, err := imports.Process(target.JoinPath(), body, &imports.Options{
		Comments:   true,
		TabIndent:  true,
		TabWidth:   8,
		FormatOnly: false,
	})
	if err != nil {
		ps.Warnf(position.Pos{}, "%s: goimports failed: %v", target.JoinPath(), err)
		return body
	}
	for _, path := range importPaths(out, target.JoinPath()) {
		if _, recorded := tracked[path]; !recorded {
			ps.Warnf(position.Pos{}, "%s: goimports added untracked import %q", target.JoinPath(), path)
		}
	}
	return out
}

// trackedPaths builds a set of import paths from the slice of
// [writer.Import] the backend recorded. The set form makes the
// "is this path tracked?" lookup in [runGoImports] O(1).
func trackedPaths(imports []writer.Import) map[string]struct{} {
	out := make(map[string]struct{}, len(imports))
	for _, imp := range imports {
		out[imp.Path] = struct{}{}
	}
	return out
}

// importPaths parses src in imports-only mode and returns each
// import declaration's path with surrounding quotes stripped. Parse
// errors return an empty slice — callers degrade gracefully.
func importPaths(src []byte, filename string) []string {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, src, parser.ImportsOnly)
	if err != nil {
		return nil
	}
	out := make([]string, 0, len(f.Imports))
	for _, imp := range f.Imports {
		path, err := strconv.Unquote(imp.Path.Value)
		if err != nil {
			continue
		}
		out = append(out, path)
	}
	return out
}
